'use client';
import { useEffect,useMemo,useRef,useState } from 'react';
import { getCurrentUser,restInsert,restSelect } from '@/lib/supabase/browser';
import styles from './AdminSupportChat.module.css';
type Thread={id:string;user_id:string;subject:string|null;status:string;updated_at:string;member_email:string|null;member_name:string|null;avatar_url?:string|null};type ProfileAvatar={id:string;avatar_url?:string|null;photo_url?:string|null;profile_image?:string|null};type Msg={id:string;thread_id:string;sender_id:string;sender_role:'member'|'admin';body:string;created_at:string};
export default function AdminSupportChat({onClose}:{onClose:()=>void}){const[threads,setThreads]=useState<Thread[]>([]);const[selected,setSelected]=useState('');const[msgs,setMsgs]=useState<Msg[]>([]);const[draft,setDraft]=useState('');const bottom=useRef<HTMLDivElement|null>(null);const composer=useRef<HTMLTextAreaElement|null>(null);const current=useMemo(()=>threads.find(x=>x.id===selected)||null,[threads,selected]);
 async function loadThreads(){const r=await restSelect<Thread[]>('support_admin_threads','select=id,user_id,subject,status,updated_at,member_email,member_name&order=updated_at.desc&limit=100');if(!r.error){const rows=r.data||[];const ids=[...new Set(rows.map(x=>x.user_id).filter(Boolean))];let avatars=new Map<string,string>();if(ids.length){const q=ids.map(id=>`\"${id}\"`).join(',');const pr=await restSelect<ProfileAvatar[]>('profiles',`select=id,avatar_url,photo_url,profile_image&id=in.(${encodeURIComponent(q)})`);if(!pr.error){avatars=new Map((pr.data||[]).map(x=>[x.id,x.avatar_url||x.photo_url||x.profile_image||'']))}}const merged=rows.map(x=>({...x,avatar_url:avatars.get(x.user_id)||null}));setThreads(merged);if(!selected&&merged[0])setSelected(merged[0].id)}}
 async function loadMessages(id:string){if(!id){setMsgs([]);return}const r=await restSelect<Msg[]>('support_messages',`select=id,thread_id,sender_id,sender_role,body,created_at&thread_id=eq.${encodeURIComponent(id)}&order=created_at.asc&limit=300`);if(!r.error)setMsgs(r.data||[])}
 useEffect(()=>{void loadThreads();const x=setInterval(()=>void loadThreads(),5000);return()=>clearInterval(x)},[]);useEffect(()=>{void loadMessages(selected);if(!selected)return;const x=setInterval(()=>void loadMessages(selected),3500);return()=>clearInterval(x)},[selected]);useEffect(()=>{
  bottom.current?.scrollIntoView({behavior:'smooth'});
},[msgs.length]);useEffect(()=>{const el=composer.current;if(!el)return;el.style.height='auto';const cs=window.getComputedStyle(el);const lh=parseFloat(cs.lineHeight)||24;const py=(parseFloat(cs.paddingTop)||0)+(parseFloat(cs.paddingBottom)||0);const by=(parseFloat(cs.borderTopWidth)||0)+(parseFloat(cs.borderBottomWidth)||0);const max=lh*7+py+by;el.style.height=`${Math.min(el.scrollHeight,max)}px`;el.style.overflowY=el.scrollHeight>max?'auto':'hidden';},[draft]);
 async function send(){const body=draft.trim();if(!body||!selected)return;const u=await getCurrentUser();if(!u?.id)return;const r=await restInsert('support_messages',{thread_id:selected,sender_id:u.id,sender_role:'admin',body,message_type:'text',metadata:{}});if(!r.error){setDraft('');await loadMessages(selected);await loadThreads()}}
 return <div className={styles.backdrop}><section className={styles.drawer}><header><div className={styles.brand}><img src="/melo-support-logo.png" alt=""/><div><strong>Melo Chat Support</strong><span>Admin Support Inbox</span></div></div><button onClick={onClose} aria-label="Close">×</button></header><div className={styles.body}><aside>{threads.length===0?<p className={styles.empty}>ยังไม่มีข้อความจากสมาชิก</p>:threads.map(x=><button key={x.id} className={x.id===selected?styles.active:''} onClick={()=>setSelected(x.id)}><div className={styles.threadRow}>{x.avatar_url?<img className={styles.avatar} src={x.avatar_url} alt=""/>:<div className={styles.avatarFallback}>{(x.member_name||x.member_email||'M').charAt(0).toUpperCase()}</div>}<div className={styles.threadCopy}><strong>{x.member_name||x.member_email||'Melo member'}</strong><span>{x.member_email||''}</span><small>{x.subject||'Support'}</small></div></div></button>)}</aside><main>{current?<><div className={styles.member}>{current.avatar_url?<img className={styles.memberAvatar} src={current.avatar_url} alt=""/>:<div className={styles.memberAvatarFallback}>{(current.member_name||current.member_email||'M').charAt(0).toUpperCase()}</div>}<div><strong>{current.member_name||'Melo member'}</strong><span>{current.member_email}</span></div></div><div className={styles.messages}>{msgs.map(m=><div key={m.id} className={`${styles.msg} ${m.sender_role==='admin'?styles.mine:''}`}><p>{m.body}</p><time>{new Date(m.created_at).toLocaleString()}</time></div>)}<div ref={bottom}/></div><footer><textarea ref={composer} rows={1} value={draft} onChange={e=>setDraft(e.target.value)} placeholder="ตอบกลับในนาม Melo Chat Support…" onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();void send()}}}/><button onClick={()=>void send()} disabled={!draft.trim()}>ส่ง</button></footer></>:<div className={styles.noSelection}><img src="/melo-support-logo.png" alt=""/><strong>Melo Chat Support</strong><span>เลือกข้อความจากสมาชิกเพื่อเริ่มตอบกลับ</span></div>}</main></div></section></div>}
