'use client';
import { useEffect, useRef, useState } from 'react';
import { useSearchParams } from 'next/navigation';
import { Header } from '@/components/Header';
import { useLocale } from '@/components/SiteProviders';
import { getCurrentUser, getStoredSession, restInsert, restSelect, rpcRequest } from '@/lib/supabase/browser';
import { bindMobileVisualViewport } from '@/lib/mobileVisualViewport';
import styles from './SupportChatExperience.module.css';
type Message={id:string;thread_id:string;sender_id:string;sender_role:'member'|'admin';body:string;created_at:string};
type ChatLanguage='th'|'en'|'de';
const copy={
 th:{title:'Melo Chat Support',sub:'พูดคุยกับทีมงาน Melo Chat',placeholder:'พิมพ์ข้อความถึงทีมงาน…',send:'ส่ง',empty:'เริ่มต้นการสนทนากับทีมงานได้ที่นี่',loading:'กำลังโหลด…',back:'กลับหน้าช่วยเหลือ',plan:'สนใจสมัครแพ็กเกจ',translation:'แปลข้อความ',on:'เปิด',off:'ปิด',original:'ข้อความต้นฉบับ'},
 en:{title:'Melo Chat Support',sub:'Chat with the Melo Chat team',placeholder:'Type a message to support…',send:'Send',empty:'Start a conversation with our support team here.',loading:'Loading…',back:'Back to Help',plan:'I am interested in the plan',translation:'Translation',on:'On',off:'Off',original:'Original'},
 de:{title:'Melo Chat Support',sub:'Chatte mit dem Melo-Chat-Team',placeholder:'Nachricht an den Support…',send:'Senden',empty:'Starte hier ein Gespräch mit unserem Support-Team.',loading:'Wird geladen…',back:'Zurück zur Hilfe',plan:'Ich interessiere mich für den Tarif',translation:'Übersetzung',on:'Ein',off:'Aus',original:'Original'}
} as const;
function lang(v:unknown,fallback:string):ChatLanguage{const x=String(v||fallback||'en').toLowerCase().replace('_','-').split('-')[0];return x==='th'||x==='de'?x:'en'}
export default function SupportChatExperience(){
 const {locale}=useLocale();const t=copy[locale as keyof typeof copy]||copy.en;const params=useSearchParams();const plan=(params.get('plan')||'').trim();
 const[threadId,setThreadId]=useState('');const[messages,setMessages]=useState<Message[]>([]);const[draft,setDraft]=useState('');const[loading,setLoading]=useState(true);const[sending,setSending]=useState(false);
 const[translationEnabled,setTranslationEnabled]=useState(false);const[targetLanguage,setTargetLanguage]=useState<ChatLanguage>(lang(locale,locale));const[translations,setTranslations]=useState<Record<string,string>>({});
 const bottom=useRef<HTMLDivElement|null>(null);const composer=useRef<HTMLTextAreaElement|null>(null);const attempted=useRef(new Set<string>());
 useEffect(()=>bindMobileVisualViewport('melo-support','calc(74px + env(safe-area-inset-bottom))'),[]);
 async function ensureThread(){const r=await rpcRequest<string>('support_ensure_my_thread',{p_subject:plan?`Plan: ${plan}`:null});if(r.error)throw new Error(r.error);const id=String(r.data||'').replaceAll('"','');setThreadId(id);return id}
 async function load(id:string){const r=await restSelect<Message[]>('support_messages',`select=id,thread_id,sender_id,sender_role,body,created_at&thread_id=eq.${encodeURIComponent(id)}&order=created_at.asc&limit=200`);if(r.error)throw new Error(r.error);setMessages(r.data||[])}
 useEffect(()=>{let live=true;const initialise=async()=>{try{const user=await getCurrentUser();if(!user?.id)return;const pref=await restSelect<Record<string,unknown>[]>('profiles',`select=primary_language&id=eq.${encodeURIComponent(user.id)}&limit=1`);if(live&&Array.isArray(pref.data)&&pref.data[0])setTargetLanguage(lang(pref.data[0].primary_language,locale));const id=await ensureThread();if(!live)return;await load(id);if(plan){const key=`melo-support-plan:${user.id}:${plan}`;if(!sessionStorage.getItem(key)){const sent=await restInsert('support_messages',{thread_id:id,sender_id:user.id,sender_role:'member',body:`${t.plan}: ${plan}`,message_type:'plan_interest',metadata:{plan}});if(!sent.error){sessionStorage.setItem(key,'1');await load(id)}}}}catch(e){console.error(e)}finally{if(live)setLoading(false)}};void initialise();return()=>{live=false}},[plan,locale]);
 useEffect(()=>{if(!threadId)return;const timer=window.setInterval(()=>{void load(threadId).catch(()=>undefined)},4000);return()=>window.clearInterval(timer)},[threadId]);
 useEffect(()=>{bottom.current?.scrollIntoView({behavior:'smooth'})},[messages.length]);
 useEffect(()=>{const el=composer.current;if(!el)return;el.style.height='auto';const cs=window.getComputedStyle(el);const lh=parseFloat(cs.lineHeight)||24;const py=(parseFloat(cs.paddingTop)||0)+(parseFloat(cs.paddingBottom)||0);const by=(parseFloat(cs.borderTopWidth)||0)+(parseFloat(cs.borderBottomWidth)||0);const max=lh*7+py+by;el.style.height=`${Math.min(el.scrollHeight,max)}px`;el.style.overflowY=el.scrollHeight>max?'auto':'hidden'},[draft]);
 useEffect(()=>{if(!translationEnabled)return;let active=true;for(const m of messages){if(m.sender_role!=='admin'||translations[m.id]||attempted.current.has(m.id)||!m.body.trim())continue;attempted.current.add(m.id);void fetch('/api/translate',{method:'POST',headers:{'Content-Type':'application/json',...(getStoredSession()?.access_token?{Authorization:`Bearer ${getStoredSession()!.access_token}`}:{})},body:JSON.stringify({text:m.body,target:targetLanguage,scope:'support'})}).then(r=>r.json()).then(x=>{const translated=typeof x?.translatedText==='string'?x.translatedText.trim():'';if(active&&translated&&translated!==m.body.trim())setTranslations(v=>({...v,[m.id]:translated}))}).catch(()=>{})}return()=>{active=false}},[translationEnabled,messages,targetLanguage,translations]);
 async function send(){const body=draft.trim();if(!body||!threadId||sending)return;setSending(true);try{const user=await getCurrentUser();if(!user?.id)return;const r=await restInsert('support_messages',{thread_id:threadId,sender_id:user.id,sender_role:'member',body,message_type:'text',metadata:{}});if(r.error)throw new Error(r.error);setDraft('');await load(threadId)}finally{setSending(false)}}
 return <div className={styles.page}><Header/><main className={styles.shell}><a href="/support" className={styles.back}>← {t.back}</a><section className={styles.chat}><header><div><h1>{t.title}</h1><p>{t.sub}</p></div><button type="button" className={`${styles.translationToggle} ${translationEnabled?styles.translationToggleOn:''}`} onClick={()=>setTranslationEnabled(v=>!v)} aria-pressed={translationEnabled}><span>文A</span><b>{t.translation}</b><em>{translationEnabled?t.on:t.off}</em></button></header><div className={styles.messages}>{loading?<p className={styles.empty}>{t.loading}</p>:messages.length===0?<p className={styles.empty}>{t.empty}</p>:messages.map(m=>{const translated=translationEnabled&&m.sender_role==='admin'?translations[m.id]||'':'';return <div key={m.id} className={`${styles.message} ${m.sender_role==='member'?styles.mine:styles.support}`}><span>{m.sender_role==='admin'?'Melo Chat Support':''}</span><p>{translated||m.body}</p>{translated?<p className={styles.original}><small>{t.original}</small>{m.body}</p>:null}<time>{new Date(m.created_at).toLocaleString(locale==='th'?'th-TH':locale==='de'?'de-DE':'en-US')}</time></div>})}<div ref={bottom}/></div><footer><textarea ref={composer} value={draft} onChange={e=>setDraft(e.target.value)} placeholder={t.placeholder} rows={1} onFocus={()=>window.setTimeout(()=>bottom.current?.scrollIntoView({block:'end'}),120)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();void send()}}}/><button type="button" disabled={!draft.trim()||sending} onClick={()=>void send()}>{t.send}</button></footer></section></main></div>}
