"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import VerifiedUserAvatar from "@/components/profile/VerifiedUserAvatar";
import {
  archiveActivity, clearTeamRole, createReminder, deleteReminder, loadAttendance, loadAudit, loadManagementState, loadReminders, loadTeam,
  removeMember, setAttendanceStatus, setLifecycle, setMembership, setTeamRole, toggleReminder, transferOwner,
  type ActivityType, type AttendanceMember, type AuditItem, type ManagementState, type Reminder, type TeamMember,
} from "./activityManagementWeb";
import styles from "./ActivityManagementModal.module.css";

type View="main"|"members"|"roles"|"attendance"|"reminders"|"audit";
const COPY={
 th:{title:"จัดการกิจกรรม",role:"บทบาทการจัดการของคุณ",ownerText:"คุณควบคุมทุกส่วนของกิจกรรมและสามารถกำหนดทีมผู้ดูแลได้",teamText:"เมนูจะแสดงเฉพาะงานที่ Owner อนุญาตให้บทบาทของคุณจัดการ",intro:"แก้ไขข้อมูล ควบคุมการรับสมาชิก และอัปเดตสถานะกิจกรรม",edit:"แก้ไขรายละเอียด",editHint:"แก้รูป รายละเอียด วันที่ สถานที่ จำนวนสมาชิก และข้อมูลอื่น ๆ",members:"จัดการสมาชิก",membersHint:"ดูรายชื่อผู้เข้าร่วมและนำสมาชิกออกเมื่อจำเป็น",roles:"Co-host, Moderator & Roles",rolesHint:"แต่งตั้งผู้ช่วย กำหนดสิทธิ์ และโอน Owner",attendance:"Attendance, Reviews & Reputation",attendanceHint:"ยืนยันผู้เข้าร่วม จัดการ No-show และเปิดดู Reputation",reminders:"Scheduled Reminders",remindersHint:"ตั้งเตือนก่อนเริ่ม 24 ชั่วโมง, 3 ชั่วโมง, Check-in, ค่าใช้จ่าย และ Safety",audit:"Activity Management History",auditHint:"ตรวจสอบว่าใครแก้ไขข้อมูล เปลี่ยนบทบาท หรือจัดการสมาชิกเมื่อใด",accept:"เปิดรับสมาชิกใหม่",acceptOn:"ขณะนี้ผู้ใช้สามารถเข้าร่วมหรือส่งคำขอได้",acceptOff:"ขณะนี้ปิดรับการเข้าร่วมและคำขอใหม่",status:"สถานะกิจกรรม",archive:"เก็บกิจกรรมเข้าคลัง",archiveAsk:"เก็บกิจกรรมเข้าคลังหรือไม่? กิจกรรมจะหายจากหน้าค้นหาสาธารณะ แต่ยังอยู่ในกิจกรรมของฉัน",close:"ปิด",back:"ย้อนกลับ",loading:"กำลังโหลด…",noAccess:"บัญชีนี้ไม่มีสิทธิ์จัดการกิจกรรม",remove:"นำออก",removeAsk:"นำสมาชิกคนนี้ออกหรือไม่?",member:"สมาชิก",cohost:"Co-host",moderator:"Moderator",transfer:"โอน Owner",transferAsk:"ยืนยันโอน Owner ให้สมาชิกคนนี้?",reputation:"Reputation",registered:"ลงทะเบียน",confirmed:"ยืนยันเข้าร่วม",noShow:"No-show",checkedIn:"เช็กอิน",addReminder:"เพิ่มการแจ้งเตือน",before24:"ก่อนเริ่ม 24 ชม.",before3:"ก่อนเริ่ม 3 ชม.",checkin:"เตือน Check-in",expense:"เตือนค่าใช้จ่าย",safety:"เตือน Safety",enabled:"เปิด",disabled:"ปิด",delete:"ลบ",noData:"ยังไม่มีข้อมูล",upcoming:"กำลังจะเกิดขึ้น",ongoing:"กำลังดำเนินอยู่",completed:"จบแล้ว",cancelled:"ยกเลิกแล้ว",active:"กำลังใช้งาน",archived:"เก็บเข้าคลัง"},
 en:{title:"Manage activity",role:"YOUR MANAGEMENT ROLE",ownerText:"You control every part of this activity and can assign the management team.",teamText:"The options below reflect the permissions assigned by the Owner.",intro:"Edit details, control membership, and update the activity status.",edit:"Edit details",editHint:"Update the image, description, date, location, capacity, and other information.",members:"Manage members",membersHint:"Review participants and remove a member when necessary.",roles:"Co-host, Moderator & Roles",rolesHint:"Assign helpers, permissions, and transfer ownership.",attendance:"Attendance, Reviews & Reputation",attendanceHint:"Confirm participants, manage no-shows, and review reputation.",reminders:"Scheduled Reminders",remindersHint:"Set reminders before start, check-in, expenses, and safety.",audit:"Activity Management History",auditHint:"See who changed details, roles, or membership and when.",accept:"Accepting new members",acceptOn:"People can currently join or apply.",acceptOff:"New joins and applications are currently closed.",status:"Activity status",archive:"Archive activity",archiveAsk:"Archive this activity? It will disappear from public discovery but remain in My Activities.",close:"Close",back:"Back",loading:"Loading…",noAccess:"You do not have permission to manage this activity.",remove:"Remove",removeAsk:"Remove this member?",member:"Member",cohost:"Co-host",moderator:"Moderator",transfer:"Transfer Owner",transferAsk:"Transfer ownership to this member?",reputation:"Reputation",registered:"Registered",confirmed:"Confirmed",noShow:"No-show",checkedIn:"Checked in",addReminder:"Add reminder",before24:"24 hours before",before3:"3 hours before",checkin:"Check-in reminder",expense:"Expense reminder",safety:"Safety reminder",enabled:"On",disabled:"Off",delete:"Delete",noData:"No data yet",upcoming:"Upcoming",ongoing:"Ongoing",completed:"Completed",cancelled:"Cancelled",active:"Active",archived:"Archived"},
 de:{title:"Aktivität verwalten",role:"DEINE VERWALTUNGSROLLE",ownerText:"Du verwaltest alle Bereiche dieser Aktivität.",teamText:"Die Optionen entsprechen deinen vom Owner vergebenen Rechten.",intro:"Details bearbeiten, Mitglieder steuern und Status aktualisieren.",edit:"Details bearbeiten",editHint:"Bild, Beschreibung, Datum, Ort, Kapazität und weitere Angaben ändern.",members:"Mitglieder verwalten",membersHint:"Teilnehmer prüfen und bei Bedarf entfernen.",roles:"Co-host, Moderator & Rollen",rolesHint:"Helfer, Rechte und Ownership verwalten.",attendance:"Teilnahme, Bewertungen & Reputation",attendanceHint:"Teilnahme bestätigen und No-shows verwalten.",reminders:"Geplante Erinnerungen",remindersHint:"Erinnerungen für Start, Check-in, Ausgaben und Safety.",audit:"Verwaltungsverlauf",auditHint:"Änderungen an Daten, Rollen und Mitgliedern prüfen.",accept:"Neue Mitglieder annehmen",acceptOn:"Beitritte und Anfragen sind offen.",acceptOff:"Neue Beitritte sind geschlossen.",status:"Aktivitätsstatus",archive:"Aktivität archivieren",archiveAsk:"Aktivität archivieren?",close:"Schließen",back:"Zurück",loading:"Wird geladen…",noAccess:"Keine Berechtigung zur Verwaltung.",remove:"Entfernen",removeAsk:"Mitglied entfernen?",member:"Mitglied",cohost:"Co-host",moderator:"Moderator",transfer:"Owner übertragen",transferAsk:"Ownership übertragen?",reputation:"Reputation",registered:"Registriert",confirmed:"Bestätigt",noShow:"No-show",checkedIn:"Eingecheckt",addReminder:"Erinnerung hinzufügen",before24:"24 Stunden vorher",before3:"3 Stunden vorher",checkin:"Check-in",expense:"Ausgaben",safety:"Safety",enabled:"An",disabled:"Aus",delete:"Löschen",noData:"Keine Daten",upcoming:"Bevorstehend",ongoing:"Läuft",completed:"Abgeschlossen",cancelled:"Abgesagt",active:"Aktiv",archived:"Archiviert"},
 zh:{title:"管理活动",role:"你的管理角色",ownerText:"你可以控制活动的全部内容并设置管理团队。",teamText:"下方选项取决于 Owner 分配给你的权限。",intro:"编辑资料、管理成员并更新活动状态。",edit:"编辑详情",editHint:"更新图片、描述、日期、地点、人数等信息。",members:"管理成员",membersHint:"查看参与者并在必要时移除成员。",roles:"共同主持、管理员与角色",rolesHint:"设置助手、权限并转移 Owner。",attendance:"出席、评价与信誉",attendanceHint:"确认参与者、管理未到场并查看信誉。",reminders:"定时提醒",remindersHint:"设置开始前、签到、费用和安全提醒。",audit:"活动管理记录",auditHint:"查看资料、角色和成员变更记录。",accept:"接受新成员",acceptOn:"当前允许加入或申请。",acceptOff:"当前关闭新加入和申请。",status:"活动状态",archive:"归档活动",archiveAsk:"确认归档此活动？",close:"关闭",back:"返回",loading:"加载中…",noAccess:"你没有管理此活动的权限。",remove:"移除",removeAsk:"确认移除此成员？",member:"成员",cohost:"共同主持",moderator:"管理员",transfer:"转移 Owner",transferAsk:"确认转移 Owner？",reputation:"信誉",registered:"已注册",confirmed:"已确认",noShow:"未到场",checkedIn:"已签到",addReminder:"添加提醒",before24:"开始前24小时",before3:"开始前3小时",checkin:"签到提醒",expense:"费用提醒",safety:"安全提醒",enabled:"开",disabled:"关",delete:"删除",noData:"暂无数据",upcoming:"即将开始",ongoing:"进行中",completed:"已结束",cancelled:"已取消",active:"启用",archived:"已归档"},
 ja:{title:"アクティビティ管理",role:"管理ロール",ownerText:"アクティビティ全体を管理し、管理チームを設定できます。",teamText:"Ownerから付与された権限に応じて機能が表示されます。",intro:"詳細、参加受付、ステータスを管理します。",edit:"詳細を編集",editHint:"画像、説明、日付、場所、定員などを更新します。",members:"メンバー管理",membersHint:"参加者を確認し必要に応じて削除します。",roles:"Co-host・Moderator・Roles",rolesHint:"管理者、権限、Owner移譲を設定します。",attendance:"出席・レビュー・評判",attendanceHint:"参加確認、No-show、評判を管理します。",reminders:"予定リマインダー",remindersHint:"開始前、Check-in、費用、安全の通知を設定します。",audit:"管理履歴",auditHint:"詳細、ロール、メンバーの変更履歴を確認します。",accept:"新規メンバー受付",acceptOn:"参加・申請を受け付けています。",acceptOff:"新規参加を停止しています。",status:"ステータス",archive:"アーカイブ",archiveAsk:"このアクティビティをアーカイブしますか？",close:"閉じる",back:"戻る",loading:"読み込み中…",noAccess:"管理権限がありません。",remove:"削除",removeAsk:"このメンバーを削除しますか？",member:"メンバー",cohost:"Co-host",moderator:"Moderator",transfer:"Ownerを移譲",transferAsk:"Ownerを移譲しますか？",reputation:"評判",registered:"登録済み",confirmed:"参加確認",noShow:"No-show",checkedIn:"Check-in済み",addReminder:"リマインダー追加",before24:"24時間前",before3:"3時間前",checkin:"Check-in",expense:"費用",safety:"Safety",enabled:"オン",disabled:"オフ",delete:"削除",noData:"データなし",upcoming:"予定",ongoing:"進行中",completed:"完了",cancelled:"キャンセル",active:"有効",archived:"アーカイブ"},
 ko:{title:"활동 관리",role:"관리 역할",ownerText:"활동 전체를 관리하고 운영 팀을 지정할 수 있습니다.",teamText:"Owner가 부여한 권한에 따라 메뉴가 표시됩니다.",intro:"세부 정보, 멤버 가입 및 활동 상태를 관리합니다.",edit:"세부 정보 수정",editHint:"이미지, 설명, 날짜, 장소, 정원 등을 수정합니다.",members:"멤버 관리",membersHint:"참가자를 확인하고 필요하면 내보냅니다.",roles:"Co-host, Moderator & Roles",rolesHint:"운영자, 권한 및 Owner 이전을 관리합니다.",attendance:"참석, 리뷰 & 평판",attendanceHint:"참석 확인, No-show 및 평판을 관리합니다.",reminders:"예약 알림",remindersHint:"시작 전, Check-in, 비용 및 Safety 알림을 설정합니다.",audit:"활동 관리 기록",auditHint:"정보, 역할 및 멤버 변경 기록을 확인합니다.",accept:"새 멤버 받기",acceptOn:"현재 가입 및 요청을 받고 있습니다.",acceptOff:"새 가입 요청을 받지 않습니다.",status:"활동 상태",archive:"활동 보관",archiveAsk:"이 활동을 보관할까요?",close:"닫기",back:"뒤로",loading:"불러오는 중…",noAccess:"활동 관리 권한이 없습니다.",remove:"내보내기",removeAsk:"이 멤버를 내보낼까요?",member:"멤버",cohost:"Co-host",moderator:"Moderator",transfer:"Owner 이전",transferAsk:"Owner를 이전할까요?",reputation:"평판",registered:"등록",confirmed:"참석 확인",noShow:"No-show",checkedIn:"Check-in",addReminder:"알림 추가",before24:"24시간 전",before3:"3시간 전",checkin:"Check-in",expense:"비용",safety:"Safety",enabled:"켜짐",disabled:"꺼짐",delete:"삭제",noData:"데이터 없음",upcoming:"예정",ongoing:"진행 중",completed:"완료",cancelled:"취소",active:"활성",archived:"보관됨"}
} as const;

function dateText(value:string){if(!value)return"—";const d=new Date(value);return Number.isNaN(d.getTime())?value:d.toLocaleString()}
function roleText(role:string,t:any){return role==="owner"?"Owner":role==="co_host"?t.cohost:role==="moderator"?t.moderator:t.member}

export default function ActivityManagementModal({open,type,id,title,locale,onClose,onChanged}:{open:boolean;type:ActivityType;id:string;title:string;locale:keyof typeof COPY;onClose:()=>void;onChanged?:()=>void}){
 const router=useRouter();const t=COPY[locale]??COPY.en;const[state,setState]=useState<ManagementState|null>(null);const[view,setView]=useState<View>("main");const[loading,setLoading]=useState(false);const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[team,setTeam]=useState<TeamMember[]>([]);const[reminders,setReminders]=useState<Reminder[]>([]);const[audit,setAudit]=useState<AuditItem[]>([]);const[attendance,setAttendance]=useState<{overview:any;members:AttendanceMember[]}|null>(null);
 async function loadMain(){setLoading(true);setError("");try{setState(await loadManagementState(type,id))}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setLoading(false)}}
 useEffect(()=>{if(open){setView("main");void loadMain()}},[open,type,id]);
 async function run(fn:()=>Promise<void>,refresh=true){if(busy)return;setBusy(true);setError("");try{await fn();if(refresh)await loadMain();onChanged?.()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 async function openView(next:View){setView(next);setLoading(true);setError("");try{if(next==="members"||next==="roles")setTeam(await loadTeam(type,id));if(next==="reminders")setReminders(await loadReminders(type,id));if(next==="audit")setAudit(await loadAudit(type,id));if(next==="attendance"&&type!=="community")setAttendance(await loadAttendance(type,id))}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setLoading(false)}}
 if(!open)return null;const statuses=type==="community"?["active","archived"]:["upcoming","ongoing","completed","cancelled"];
 function edit(){router.push(type==="trip"?`/edit-trip/${id}`:type==="event"?`/edit-event/${id}`:`/edit-community/${id}`);onClose()}
 const header=<header className={styles.header}><button onClick={()=>view==="main"?onClose():setView("main")}>{view==="main"?"×":"‹"}</button><div><h2>{view==="main"?t.title:view==="members"?t.members:view==="roles"?t.roles:view==="attendance"?t.attendance:view==="reminders"?t.reminders:t.audit}</h2><p>{title}</p></div><span/></header>;
 return <div className={styles.backdrop} onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section className={styles.modal} role="dialog" aria-modal="true">{header}<div className={styles.scroll}>
  {loading?<div className={styles.state}>{t.loading}</div>:error?<div className={styles.error}>{error}<button onClick={()=>view==="main"?void loadMain():void openView(view)}>↻</button></div>:view==="main"?<>{!state?<div className={styles.state}>{t.noData}</div>:!state.canManage?<div className={styles.state}>{t.noAccess}</div>:<>
   <div className={styles.roleCard}><b>{roleText(state.role,t)}</b><div><small>{t.role}</small><p>{state.isOwner?t.ownerText:t.teamText}</p></div></div><p className={styles.intro}>{t.intro}</p>
   <div className={styles.cards}>{state.canEdit?<Action icon="✎" title={t.edit} hint={t.editHint} onClick={edit}/>:null}{state.canMembers?<Action icon="♙" title={t.members} hint={t.membersHint} badge={state.memberCount} onClick={()=>void openView("members")}/>:null}<Action icon="♜" title={t.roles} hint={t.rolesHint} onClick={()=>void openView("roles")}/>{type!=="community"&&state.canAttendance?<Action icon="✓" title={t.attendance} hint={t.attendanceHint} onClick={()=>void openView("attendance")}/>:null}{type!=="community"&&state.canReminders?<Action icon="◷" title={t.reminders} hint={t.remindersHint} onClick={()=>void openView("reminders")}/>:null}{state.canAudit?<Action icon="≡" title={t.audit} hint={t.auditHint} onClick={()=>void openView("audit")}/>:null}</div>
   {state.canMembers?<section className={styles.settingCard}><div><h3>{t.accept}</h3><p>{state.membershipOpen?t.acceptOn:t.acceptOff}</p></div><button className={styles.switch} data-on={state.membershipOpen} disabled={busy||Boolean(state.archivedAt)} onClick={()=>void run(()=>setMembership(type,id,!state.membershipOpen))}><span/></button></section>:null}
   {state.canEdit?<section className={styles.settingCardBlock}><h3>{t.status}</h3><div className={styles.chips}>{statuses.map(status=><button key={status} data-active={state.lifecycle===status} disabled={busy||Boolean(state.archivedAt)} onClick={()=>void run(()=>setLifecycle(type,id,status as any))}>{(t as any)[status]}</button>)}</div></section>:null}
   {state.isOwner&&!state.archivedAt?<button className={styles.archive} disabled={busy} onClick={()=>{if(confirm(t.archiveAsk))void run(async()=>{await archiveActivity(type,id);onClose()})}}>{t.archive}</button>:null}
  </>}</>:view==="members"?<MemberView team={team} t={t} busy={busy} onRemove={m=>{if(confirm(t.removeAsk))void run(async()=>{await removeMember(type,id,m.userId);setTeam(await loadTeam(type,id))},false)}}/>:view==="roles"?<RolesView team={team} t={t} busy={busy} canRoles={Boolean(state?.canRoles)} canTransfer={Boolean(state?.canTransfer)} onRole={(m,r)=>void run(async()=>{if(r==="member")await clearTeamRole(type,id,m.userId);else await setTeamRole(type,id,m.userId,r);setTeam(await loadTeam(type,id))},false)} onTransfer={m=>{if(confirm(t.transferAsk))void run(async()=>{await transferOwner(type,id,m.userId);setTeam(await loadTeam(type,id));await loadMain()},false)}}/>:view==="attendance"&&type!=="community"?<AttendanceView data={attendance} t={t} busy={busy} onStatus={(m,s)=>void run(async()=>{await setAttendanceStatus(type,id,m.userId,s);setAttendance(await loadAttendance(type,id))},false)}/>:view==="reminders"&&type!=="community"?<ReminderView items={reminders} t={t} busy={busy} onAdd={(kind,offset)=>void run(async()=>{await createReminder(type,id,kind,offset);setReminders(await loadReminders(type,id))},false)} onToggle={(r,on)=>void run(async()=>{await toggleReminder(r.id,on);setReminders(await loadReminders(type,id))},false)} onDelete={r=>void run(async()=>{await deleteReminder(r.id);setReminders(await loadReminders(type,id))},false)}/>:<AuditView items={audit} t={t}/>} 
 </div></section></div>
}
function Action({icon,title,hint,badge,onClick}:{icon:string;title:string;hint:string;badge?:number;onClick:()=>void}){return <button className={styles.action} onClick={onClick}><span>{icon}</span><div><strong>{title}</strong><small>{hint}</small></div>{badge!=null?<b>{badge}</b>:null}<em>›</em></button>}
function MemberView({team,t,busy,onRemove}:{team:TeamMember[];t:any;busy:boolean;onRemove:(m:TeamMember)=>void}){return <div className={styles.people}>{team.length?team.map(m=><article key={m.userId}><VerifiedUserAvatar userId={m.userId} name={m.name} src={m.photoUrl} size={46}/><div><strong><Link href={`/users/${m.userId}`} className={styles.userNameLink}>{m.name}</Link></strong><small>{roleText(m.role,t)} · {m.language.toUpperCase()}</small></div>{!m.isOwner?<button disabled={busy} onClick={()=>onRemove(m)}>{t.remove}</button>:null}</article>):<div className={styles.state}>{t.noData}</div>}</div>}
function RolesView({team,t,busy,canRoles,canTransfer,onRole,onTransfer}:{team:TeamMember[];t:any;busy:boolean;canRoles:boolean;canTransfer:boolean;onRole:(m:TeamMember,r:"member"|"co_host"|"moderator")=>void;onTransfer:(m:TeamMember)=>void}){return <div className={styles.people}>{team.map(m=><article key={m.userId}><VerifiedUserAvatar userId={m.userId} name={m.name} src={m.photoUrl} size={46}/><div><strong><Link href={`/users/${m.userId}`} className={styles.userNameLink}>{m.name}</Link></strong><small>{roleText(m.role,t)}</small></div>{!m.isOwner&&canRoles?<select disabled={busy} value={m.role==="owner"?"member":m.role} onChange={e=>onRole(m,e.target.value as any)}><option value="member">{t.member}</option><option value="co_host">{t.cohost}</option><option value="moderator">{t.moderator}</option></select>:null}{!m.isOwner&&canTransfer?<button disabled={busy} onClick={()=>onTransfer(m)}>{t.transfer}</button>:null}</article>)}</div>}
function AttendanceView({data,t,busy,onStatus}:{data:{overview:any;members:AttendanceMember[]}|null;t:any;busy:boolean;onStatus:(m:AttendanceMember,s:"registered"|"confirmed"|"no_show")=>void}){if(!data)return <div className={styles.state}>{t.noData}</div>;return <><div className={styles.metrics}><span><b>{data.overview.memberCount}</b>{t.member}</span><span><b>{data.overview.checkedIn}</b>{t.checkedIn}</span><span><b>{data.overview.confirmed}</b>{t.confirmed}</span><span><b>{data.overview.noShow}</b>{t.noShow}</span></div><div className={styles.people}>{data.members.map(m=><article key={m.userId}><VerifiedUserAvatar userId={m.userId} name={m.name} src={m.photoUrl} size={46}/><div><strong><Link href={`/users/${m.userId}`} className={styles.userNameLink}>{m.name}</Link></strong><small>{m.status} · ★ {m.reputation.toFixed(1)}</small><Link href={`/reputation/${m.userId}`}>{t.reputation} →</Link></div><select disabled={busy} value={["registered","confirmed","no_show"].includes(m.status)?m.status:"registered"} onChange={e=>onStatus(m,e.target.value as any)}><option value="registered">{t.registered}</option><option value="confirmed">{t.confirmed}</option><option value="no_show">{t.noShow}</option></select></article>)}</div></>}
function ReminderView({items,t,busy,onAdd,onToggle,onDelete}:{items:Reminder[];t:any;busy:boolean;onAdd:(k:string,o:number)=>void;onToggle:(r:Reminder,v:boolean)=>void;onDelete:(r:Reminder)=>void}){const templates:[[string,number,string]]|any=[["before_start",1440,t.before24],["before_start",180,t.before3],["check_in",0,t.checkin],["expense_due",0,t.expense],["safety_check_in",0,t.safety]];return <><div className={styles.templateRow}>{templates.map(([k,o,l]:[string,number,string])=><button disabled={busy} key={`${k}-${o}`} onClick={()=>onAdd(k,o)}>＋ {l}</button>)}</div><div className={styles.reminders}>{items.length?items.map(r=><article key={r.id}><div><strong>{r.type.replaceAll("_"," ")}</strong><small>{dateText(r.scheduledAt)} · {r.creator}</small></div><button data-on={r.enabled} disabled={busy} onClick={()=>onToggle(r,!r.enabled)}>{r.enabled?t.enabled:t.disabled}</button><button className={styles.dangerText} disabled={busy} onClick={()=>onDelete(r)}>{t.delete}</button></article>):<div className={styles.state}>{t.noData}</div>}</div></>}
function AuditView({items,t}:{items:AuditItem[];t:any}){return <div className={styles.audit}>{items.length?items.map(i=><article key={i.id}><span>≡</span><div><strong>{i.action.replaceAll("_"," ")}</strong><p>{i.actor}{i.target?` → ${i.target}`:""}</p><small>{dateText(i.createdAt)}</small></div></article>):<div className={styles.state}>{t.noData}</div>}</div>}
