"use client";

import Link from "next/link";
import { useEffect, useMemo, useRef, useState } from "react";
import VerifiedUserAvatar from "@/components/profile/VerifiedUserAvatar";
import {
  createExpense, deleteAlbum, deleteExpense, deleteSettlement, loadAlbum, loadTripExpenses, recordSettlement, uploadAlbum,
  type AlbumItem, type BalanceItem, type ExpenseItem, type ExpenseMember, type SettlementItem,
} from "./tripSharedToolsWeb";
import styles from "./TripSharedToolsModal.module.css";

type Mode="expense"|"album"|null;
const CURRENCIES=["THB","USD","EUR","JPY","KRW","CNY"];
const COPY={
  th:{expense:"Shared Expense",album:"Trip Album",close:"ปิด",loading:"กำลังโหลด…",retry:"ลองอีกครั้ง",addExpense:"เพิ่มค่าใช้จ่าย",settle:"บันทึกการชำระ",summary:"สรุปค่าใช้จ่าย",expenses:"รายการค่าใช้จ่าย",balances:"ยอดคงเหลือ",settlements:"การชำระระหว่างสมาชิก",noExpense:"ยังไม่มีค่าใช้จ่ายในทริปนี้",title:"รายการ",amount:"จำนวนเงิน",date:"วันที่",notes:"หมายเหตุ",participants:"ผู้ร่วมจ่าย",allMembers:"เลือกทุกคน",save:"บันทึก",cancel:"ยกเลิก",paidBy:"จ่ายโดย",myShare:"ส่วนของฉัน",delete:"ลบ",to:"ผู้รับเงิน",albumHint:"สมาชิกที่ได้รับอนุมัติเท่านั้นที่ดูและเพิ่มรูปได้ รูปทั้งหมดเก็บในพื้นที่ Private",photos:"รูปในอัลบั้ม",addPhoto:"เพิ่มรูป",caption:"คำบรรยาย",upload:"อัปโหลดเข้าอัลบั้ม",noPhotos:"ยังไม่มีรูปในทริปนี้",choosePhoto:"เลือกรูปภาพ",confirmDelete:"ยืนยันลบรายการนี้หรือไม่?"},
  en:{expense:"Shared Expense",album:"Trip Album",close:"Close",loading:"Loading…",retry:"Try again",addExpense:"Add expense",settle:"Record settlement",summary:"Expense summary",expenses:"Expenses",balances:"Balances",settlements:"Settlements",noExpense:"No shared expenses yet",title:"Title",amount:"Amount",date:"Date",notes:"Notes",participants:"Participants",allMembers:"Select all",save:"Save",cancel:"Cancel",paidBy:"Paid by",myShare:"My share",delete:"Delete",to:"Pay to",albumHint:"Only approved members can view and add photos. Album images are stored privately.",photos:"photos in album",addPhoto:"Add photo",caption:"Caption",upload:"Upload to album",noPhotos:"No photos in this trip yet",choosePhoto:"Choose photo",confirmDelete:"Delete this item?"},
  de:{expense:"Gemeinsame Ausgaben",album:"Trip Album",close:"Schließen",loading:"Wird geladen…",retry:"Erneut",addExpense:"Ausgabe hinzufügen",settle:"Zahlung erfassen",summary:"Zusammenfassung",expenses:"Ausgaben",balances:"Salden",settlements:"Zahlungen",noExpense:"Noch keine Ausgaben",title:"Titel",amount:"Betrag",date:"Datum",notes:"Notizen",participants:"Teilnehmer",allMembers:"Alle auswählen",save:"Speichern",cancel:"Abbrechen",paidBy:"Bezahlt von",myShare:"Mein Anteil",delete:"Löschen",to:"Empfänger",albumHint:"Nur bestätigte Mitglieder können Fotos ansehen und hinzufügen.",photos:"Fotos im Album",addPhoto:"Foto hinzufügen",caption:"Bildunterschrift",upload:"Hochladen",noPhotos:"Noch keine Fotos",choosePhoto:"Foto wählen",confirmDelete:"Diesen Eintrag löschen?"},
  zh:{expense:"共享费用",album:"旅行相册",close:"关闭",loading:"加载中…",retry:"重试",addExpense:"添加费用",settle:"记录结算",summary:"费用汇总",expenses:"费用",balances:"余额",settlements:"成员结算",noExpense:"暂无共享费用",title:"项目",amount:"金额",date:"日期",notes:"备注",participants:"参与者",allMembers:"全选",save:"保存",cancel:"取消",paidBy:"付款人",myShare:"我的份额",delete:"删除",to:"收款人",albumHint:"仅已批准成员可以查看和添加照片，图片存储在私有空间。",photos:"张照片",addPhoto:"添加照片",caption:"说明",upload:"上传到相册",noPhotos:"此旅行暂无照片",choosePhoto:"选择照片",confirmDelete:"确认删除此项目？"},
  ja:{expense:"共有費用",album:"Trip Album",close:"閉じる",loading:"読み込み中…",retry:"再試行",addExpense:"費用を追加",settle:"精算を記録",summary:"費用サマリー",expenses:"費用",balances:"残高",settlements:"精算",noExpense:"共有費用はまだありません",title:"項目",amount:"金額",date:"日付",notes:"メモ",participants:"参加者",allMembers:"全員選択",save:"保存",cancel:"キャンセル",paidBy:"支払者",myShare:"自分の負担",delete:"削除",to:"受取人",albumHint:"承認済みメンバーのみ写真を閲覧・追加できます。写真は非公開領域に保存されます。",photos:"枚",addPhoto:"写真を追加",caption:"キャプション",upload:"アルバムへアップロード",noPhotos:"写真はまだありません",choosePhoto:"写真を選択",confirmDelete:"この項目を削除しますか？"},
  ko:{expense:"공동 경비",album:"Trip Album",close:"닫기",loading:"불러오는 중…",retry:"다시 시도",addExpense:"경비 추가",settle:"정산 기록",summary:"경비 요약",expenses:"경비",balances:"잔액",settlements:"정산",noExpense:"공동 경비가 아직 없습니다",title:"항목",amount:"금액",date:"날짜",notes:"메모",participants:"참여자",allMembers:"전체 선택",save:"저장",cancel:"취소",paidBy:"결제자",myShare:"내 부담",delete:"삭제",to:"받는 사람",albumHint:"승인된 멤버만 사진을 보고 추가할 수 있습니다. 사진은 비공개 저장소에 보관됩니다.",photos:"장",addPhoto:"사진 추가",caption:"설명",upload:"앨범에 업로드",noPhotos:"아직 사진이 없습니다",choosePhoto:"사진 선택",confirmDelete:"이 항목을 삭제할까요?"},
} as const;
function money(value:number,currency:string){try{return new Intl.NumberFormat(undefined,{style:"currency",currency,maximumFractionDigits:["JPY","KRW"].includes(currency)?0:2}).format(value)}catch{return `${currency} ${value.toLocaleString()}`}}
function today(){const d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,10)}

export default function TripSharedToolsModal({mode,tripId,title,locale,onClose}:{mode:Mode;tripId:string;title:string;locale:keyof typeof COPY;onClose:()=>void}){
  const t=COPY[locale]??COPY.en; const [loading,setLoading]=useState(false);const[error,setError]=useState("");const[busy,setBusy]=useState(false);
  const[members,setMembers]=useState<ExpenseMember[]>([]);const[expenses,setExpenses]=useState<ExpenseItem[]>([]);const[balances,setBalances]=useState<BalanceItem[]>([]);const[settlements,setSettlements]=useState<SettlementItem[]>([]);const[album,setAlbum]=useState<AlbumItem[]>([]);
  const[form,setForm]=useState<"expense"|"settle"|"photo"|null>(null);const[file,setFile]=useState<File|null>(null);const fileRef=useRef<HTMLInputElement>(null);
  const[expenseTitle,setExpenseTitle]=useState("");const[amount,setAmount]=useState("");const[currency,setCurrency]=useState("THB");const[date,setDate]=useState(today());const[notes,setNotes]=useState("");const[selected,setSelected]=useState<string[]>([]);const[toUser,setToUser]=useState("");const[caption,setCaption]=useState("");
  async function load(){if(!mode)return;setLoading(true);setError("");try{if(mode==="expense"){const data=await loadTripExpenses(tripId);setMembers(data.members);setExpenses(data.expenses);setBalances(data.balances);setSettlements(data.settlements);if(!selected.length)setSelected(data.members.map(m=>m.userId));if(!toUser)setToUser(data.members.find(m=>!m.isMe)?.userId??"");}else setAlbum(await loadAlbum(tripId));}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setLoading(false)}}
  useEffect(()=>{if(mode)void load();},[mode,tripId]);
  const totals=useMemo(()=>Object.entries(expenses.reduce<Record<string,number>>((acc,item)=>{acc[item.currency]=(acc[item.currency]??0)+item.amount;return acc},{})),[expenses]);
  if(!mode)return null;
  async function run(fn:()=>Promise<void>){if(busy)return;setBusy(true);setError("");try{await fn();setForm(null);setFile(null);setCaption("");setExpenseTitle("");setAmount("");setNotes("");await load()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
  function toggle(id:string){setSelected(current=>current.includes(id)?current.filter(x=>x!==id):[...current,id])}
  return <div className={styles.backdrop} onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section className={styles.modal} role="dialog" aria-modal="true">
    <header className={styles.header}><div><small>{mode==="expense"?"SHARED EXPENSE":"TRIP ALBUM"}</small><h2>{mode==="expense"?t.expense:t.album}</h2><p>{title}</p></div><button onClick={onClose}>×</button></header>
    {loading?<div className={styles.state}>{t.loading}</div>:error?<div className={styles.error}>{error}<button onClick={()=>void load()}>{t.retry}</button></div>:mode==="expense"?<div className={styles.body}>
      <div className={styles.heroActions}><div className={styles.summary}>{totals.length?totals.map(([c,v])=><span key={c}><small>{t.summary}</small><strong>{money(v,c)}</strong></span>):<span><small>{t.summary}</small><strong>—</strong></span>}</div><div><button className={styles.primary} onClick={()=>{setForm("expense");setSelected(members.map(m=>m.userId));setDate(today())}}>＋ {t.addExpense}</button><button onClick={()=>setForm("settle")}>↔ {t.settle}</button></div></div>
      {form==="expense"?<div className={styles.form}><h3>{t.addExpense}</h3><div className={styles.formGrid}><label><span>{t.title}</span><input value={expenseTitle} onChange={e=>setExpenseTitle(e.target.value)}/></label><label><span>{t.amount}</span><input type="number" min="0" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label><span>Currency</span><select value={currency} onChange={e=>setCurrency(e.target.value)}>{CURRENCIES.map(c=><option key={c}>{c}</option>)}</select></label><label><span>{t.date}</span><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label></div><label><span>{t.notes}</span><textarea value={notes} onChange={e=>setNotes(e.target.value)} maxLength={500}/></label><div className={styles.memberSelectHead}><strong>{t.participants}</strong><button onClick={()=>setSelected(selected.length===members.length?[]:members.map(m=>m.userId))}>{t.allMembers}</button></div><div className={styles.memberChecks}>{members.map(m=><button key={m.userId} data-active={selected.includes(m.userId)} onClick={()=>toggle(m.userId)}><VerifiedUserAvatar userId={m.userId} name={m.name} src={m.photoUrl} size={32}/><span>{m.name}</span><b>{selected.includes(m.userId)?"✓":""}</b></button>)}</div><div className={styles.formActions}><button onClick={()=>setForm(null)}>{t.cancel}</button><button className={styles.primary} disabled={busy} onClick={()=>void run(async()=>{const n=Number(amount);if(!expenseTitle.trim()||!Number.isFinite(n)||n<=0||!selected.length)throw new Error("Please complete the expense information");await createExpense({tripId,title:expenseTitle,amount:n,currency,participants:selected,date,notes})})}>{t.save}</button></div></div>:null}
      {form==="settle"?<div className={styles.form}><h3>{t.settle}</h3><div className={styles.formGrid}><label><span>{t.to}</span><select value={toUser} onChange={e=>setToUser(e.target.value)}>{members.filter(m=>!m.isMe).map(m=><option key={m.userId} value={m.userId}>{m.name}</option>)}</select></label><label><span>{t.amount}</span><input type="number" min="0" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label><span>Currency</span><select value={currency} onChange={e=>setCurrency(e.target.value)}>{CURRENCIES.map(c=><option key={c}>{c}</option>)}</select></label></div><label><span>{t.notes}</span><textarea value={notes} onChange={e=>setNotes(e.target.value)} maxLength={500}/></label><div className={styles.formActions}><button onClick={()=>setForm(null)}>{t.cancel}</button><button className={styles.primary} disabled={busy} onClick={()=>void run(async()=>{const n=Number(amount);if(!toUser||!Number.isFinite(n)||n<=0)throw new Error("Please complete the settlement information");await recordSettlement({tripId,toUserId:toUser,amount:n,currency,note:notes})})}>{t.save}</button></div></div>:null}
      <section><h3>{t.balances}</h3><div className={styles.balanceGrid}>{balances.length?balances.map((b,i)=><article key={`${b.userId}-${b.currency}-${i}`}><VerifiedUserAvatar userId={b.userId} name={b.name} size={38}/><div><strong><Link href={`/users/${b.userId}`} className={styles.userNameLink}>{b.name}</Link></strong><small>{b.currency}</small></div><em data-positive={b.net>=0}>{b.net>=0?"+":""}{money(b.net,b.currency)}</em></article>):<p className={styles.empty}>{t.noExpense}</p>}</div></section>
      <section><h3>{t.expenses}</h3><div className={styles.list}>{expenses.length?expenses.map(item=><article key={item.id}><div><strong>{item.title}</strong><small>{t.paidBy} <Link href={`/users/${item.paidBy}`} className={styles.userNameLink}>{item.payerName}</Link> · {item.date}</small>{item.notes?<p>{item.notes}</p>:null}</div><div className={styles.amount}><strong>{money(item.amount,item.currency)}</strong><small>{t.myShare}: {money(item.myShare,item.currency)}</small>{item.canDelete?<button onClick={()=>{if(confirm(t.confirmDelete))void run(()=>deleteExpense(item.id))}}>{t.delete}</button>:null}</div></article>):<p className={styles.empty}>{t.noExpense}</p>}</div></section>
      {settlements.length?<section><h3>{t.settlements}</h3><div className={styles.list}>{settlements.map(item=><article key={item.id}><div><strong><Link href={`/users/${item.fromId}`} className={styles.userNameLink}>{item.fromName}</Link> → <Link href={`/users/${item.toId}`} className={styles.userNameLink}>{item.toName}</Link></strong><small>{new Date(item.createdAt).toLocaleString()}</small>{item.note?<p>{item.note}</p>:null}</div><div className={styles.amount}><strong>{money(item.amount,item.currency)}</strong>{item.canDelete?<button onClick={()=>{if(confirm(t.confirmDelete))void run(()=>deleteSettlement(item.id))}}>{t.delete}</button>:null}</div></article>)}</div></section>:null}
    </div>:<div className={styles.body}>
      <div className={styles.albumHero}><div><strong>{album.length} {t.photos}</strong><p>{t.albumHint}</p></div><button className={styles.primary} onClick={()=>{setForm("photo");fileRef.current?.click()}}>＋ {t.addPhoto}</button></div>
      <input ref={fileRef} type="file" accept="image/*" hidden onChange={e=>{const picked=e.target.files?.[0]??null;setFile(picked);if(picked)setForm("photo")}}/>
      {form==="photo"?<div className={styles.form}><h3>{t.addPhoto}</h3>{file?<div className={styles.preview}><img src={URL.createObjectURL(file)} alt=""/></div>:<button onClick={()=>fileRef.current?.click()}>{t.choosePhoto}</button>}<label><span>{t.caption}</span><textarea value={caption} onChange={e=>setCaption(e.target.value)} maxLength={500}/></label><div className={styles.formActions}><button onClick={()=>{setForm(null);setFile(null)}}>{t.cancel}</button><button className={styles.primary} disabled={busy||!file} onClick={()=>file&&void run(()=>uploadAlbum(tripId,file,caption))}>{t.upload}</button></div></div>:null}
      {album.length?<div className={styles.albumGrid}>{album.map(item=><article key={item.id}>{item.signedUrl?<img src={item.signedUrl} alt={item.caption||item.uploaderName}/>:<div className={styles.noImage}>▧</div>}<div><strong><Link href={`/users/${item.uploaderId}`} className={styles.userNameLink}>{item.uploaderName}</Link></strong><p>{item.caption||"—"}</p><small>{new Date(item.createdAt).toLocaleString()}</small>{item.canDelete?<button onClick={()=>{if(confirm(t.confirmDelete))void run(()=>deleteAlbum(item))}}>{t.delete}</button>:null}</div></article>)}</div>:<div className={styles.state}><strong>{t.noPhotos}</strong><button className={styles.primary} onClick={()=>fileRef.current?.click()}>{t.choosePhoto}</button></div>}
    </div>}
  </section></div>
}
