-- Melo Chat Lite - Admin Center V2: stable ME member codes + package assignment
create table if not exists public.member_registry (
  user_id uuid primary key references auth.users(id) on delete cascade,
  member_number bigint generated by default as identity unique,
  created_at timestamptz not null default now()
);

alter table public.member_registry enable row level security;
revoke all on public.member_registry from anon, authenticated;

insert into public.member_registry(user_id,created_at)
select u.id,u.created_at from auth.users u
where not exists(select 1 from public.member_registry m where m.user_id=u.id)
order by u.created_at,u.id;

create or replace function public.ensure_member_registry() returns trigger
language plpgsql security definer set search_path=public as $$
begin
  insert into public.member_registry(user_id) values(new.id) on conflict(user_id) do nothing;
  return new;
end $$;

drop trigger if exists trg_ensure_member_registry on auth.users;
create trigger trg_ensure_member_registry after insert on auth.users
for each row execute function public.ensure_member_registry();

create or replace function public.admin_center_list_users()
returns table(user_id uuid,member_code text,email text,full_name text,avatar_url text,plan_id uuid,plan_name text,plan_expires_at timestamptz,is_verified boolean,report_count bigint,is_suspended boolean)
language sql security definer set search_path=public,auth as $$
 select u.id,
   'ME'||lpad(m.member_number::text,6,'0'),
   u.email,
   coalesce(nullif(trim(concat_ws(' ',p.first_name,p.last_name)),''),p.display_name,u.raw_user_meta_data->>'full_name','Melo member'),
   coalesce(case when cardinality(p.photo_paths)>0 then p.photo_paths[1] else null end,u.raw_user_meta_data->>'avatar_url'),
   us.plan_id,coalesce(sp.name,'Free'),us.expires_at,
   public.get_public_identity_verification(u.id),
   (select count(*) from public.user_reports r where r.reported_user_id=u.id),
   coalesce(st.is_suspended,false)
 from auth.users u
 left join public.member_registry m on m.user_id=u.id
 left join public.profiles p on p.id=u.id
 left join lateral (select * from public.user_subscriptions x where x.user_id=u.id and x.status='active' order by x.expires_at desc nulls last,x.created_at desc limit 1) us on true
 left join public.subscription_plans sp on sp.id=us.plan_id
 left join public.user_admin_status st on st.user_id=u.id
 where public.is_admin_center_admin()
 order by u.created_at desc;
$$;
grant execute on function public.admin_center_list_users() to authenticated;

create or replace function public.admin_center_assign_plan(p_user_id uuid,p_plan_id uuid)
returns boolean language plpgsql security definer set search_path=public,auth as $$
declare v_plan public.subscription_plans%rowtype;
begin
 if not public.is_admin_center_admin() then raise exception 'admin only'; end if;
 select * into v_plan from public.subscription_plans where id=p_plan_id and is_active=true;
 if v_plan.id is null then raise exception 'package not found or inactive'; end if;
 update public.user_subscriptions set status='replaced' where user_id=p_user_id and status='active';
 insert into public.user_subscriptions(user_id,plan_id,starts_at,expires_at,status)
 values(p_user_id,v_plan.id,now(),now()+make_interval(days=>greatest(1,v_plan.duration_days)),'active');
 insert into public.package_transactions(user_id,plan_id,transaction_type,amount,note)
 values(p_user_id,v_plan.id,'admin_package_change',0,'Package assigned by admin');
 return true;
end $$;
grant execute on function public.admin_center_assign_plan(uuid,uuid) to authenticated;
