'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { useLocale } from '@/components/SiteProviders';
import PartnerModeHeader from './PartnerModeHeader';
import { saveMyBusinessAccountDraft, submitMyBusinessAccountForReview } from './partnerModeWeb';
import styles from './PartnerMode.module.css';

const COPY={th:{title:'สร้างบัญชีธุรกิจ',body:'กรอกข้อมูลหลักของร้านเพื่อส่งให้ Admin ตรวจสอบ',save:'บันทึกและส่งตรวจ',sent:'ส่งข้อมูลให้ Admin ตรวจสอบแล้ว'},en:{title:'Create business account',body:'Enter your business details and submit them for admin review.',save:'Save & submit for review',sent:'Submitted for admin review'},de:{title:'Geschäftskonto erstellen',body:'Geschäftsdaten eingeben und zur Prüfung senden.',save:'Speichern & senden',sent:'Zur Prüfung gesendet'},zh:{title:'创建商家账号',body:'填写商家资料并提交管理员审核。',save:'保存并提交审核',sent:'已提交管理员审核'},ja:{title:'ビジネスアカウント作成',body:'店舗情報を入力してAdmin審査へ送信します。',save:'保存して審査へ送信',sent:'審査へ送信しました'},ko:{title:'비즈니스 계정 만들기',body:'매장 정보를 입력하고 관리자 검토를 요청하세요.',save:'저장 및 검토 요청',sent:'관리자 검토를 요청했습니다'}} as const;
export default function PartnerOnboardingExperience(){const {locale}=useLocale();const t=COPY[locale]??COPY.en;const router=useRouter();const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [form,setForm]=useState({businessType:'food_drink',legalName:'',displayName:'',description:'',address:'',city:'',country:'Thailand',phone:'',email:'',website:'',primaryLanguage:locale,partnershipModes:['partner'] as string[]});
 function set<K extends keyof typeof form>(key:K,value:(typeof form)[K]){setForm(v=>({...v,[key]:value}))}
 async function submit(e:React.FormEvent){e.preventDefault();if(busy)return;setBusy(true);setMessage('');try{const id=await saveMyBusinessAccountDraft(form);await submitMyBusinessAccountForReview(id);setMessage(t.sent);window.setTimeout(()=>router.replace('/partner'),900)}catch(err){setMessage(err instanceof Error?err.message:String(err))}finally{setBusy(false)}}
 return <main className={styles.partnerPage}><PartnerModeHeader access={null}/><section className={styles.partnerShell}><header className={styles.pageTitle}><div><small>MELO PARTNER</small><h1>{t.title}</h1><p>{t.body}</p></div></header><form className={styles.partnerOnboarding} onSubmit={submit}><div className={styles.partnerFormGrid}><label>Business type<select value={form.businessType} onChange={e=>set('businessType',e.target.value)}><option value="food_drink">Food & drink</option><option value="hotel">Hotel / lodging</option><option value="travel">Travel</option><option value="activity">Activity</option><option value="service">Service</option><option value="retail">Retail</option></select></label><label>Primary language<select value={form.primaryLanguage} onChange={e=>set('primaryLanguage',e.target.value as any)}><option value="th">ไทย</option><option value="en">English</option><option value="de">Deutsch</option><option value="zh">中文</option><option value="ja">日本語</option><option value="ko">한국어</option></select></label><label>Legal name<input required value={form.legalName} onChange={e=>set('legalName',e.target.value)}/></label><label>Display name<input required value={form.displayName} onChange={e=>set('displayName',e.target.value)}/></label><label>City<input required value={form.city} onChange={e=>set('city',e.target.value)}/></label><label>Country<input required value={form.country} onChange={e=>set('country',e.target.value)}/></label><label>Phone<input required value={form.phone} onChange={e=>set('phone',e.target.value)}/></label><label>Email<input type="email" required value={form.email} onChange={e=>set('email',e.target.value)}/></label><label>Website<input value={form.website} onChange={e=>set('website',e.target.value)}/></label><label>Address<input required value={form.address} onChange={e=>set('address',e.target.value)}/></label></div><label>Description<textarea value={form.description} onChange={e=>set('description',e.target.value)}/></label>{message?<div className={styles.notice}>{message}</div>:null}<button className={styles.primaryButton} disabled={busy||!form.displayName.trim()||!form.legalName.trim()}>{t.save}</button></form></section></main>}
