'use client';
import { useEffect, useMemo, useRef, useState } from 'react';
import styles from './NationalityCombobox.module.css';

export const NATIONALITIES = [
'Afghan','Albanian','Algerian','American','Andorran','Angolan','Antiguan and Barbudan','Argentine','Armenian','Australian','Austrian','Azerbaijani','Bahamian','Bahraini','Bangladeshi','Barbadian','Belarusian','Belgian','Belizean','Beninese','Bhutanese','Bolivian','Bosnian and Herzegovinian','Botswanan','Brazilian','British','Bruneian','Bulgarian','Burkinabé','Burundian','Cabo Verdean','Cambodian','Cameroonian','Canadian','Central African','Chadian','Chilean','Chinese','Colombian','Comorian','Congolese','Costa Rican','Croatian','Cuban','Cypriot','Czech','Danish','Djiboutian','Dominican','Dutch','Ecuadorian','Egyptian','Emirati','Equatorial Guinean','Eritrean','Estonian','Eswatini','Ethiopian','Fijian','Filipino','Finnish','French','Gabonese','Gambian','Georgian','German','Ghanaian','Greek','Grenadian','Guatemalan','Guinean','Guyanese','Haitian','Honduran','Hungarian','Icelandic','Indian','Indonesian','Iranian','Iraqi','Irish','Israeli','Italian','Ivorian','Jamaican','Japanese','Jordanian','Kazakh','Kenyan','Kiribati','Kuwaiti','Kyrgyz','Lao','Latvian','Lebanese','Liberian','Libyan','Liechtensteiner','Lithuanian','Luxembourgish','Malagasy','Malawian','Malaysian','Maldivian','Malian','Maltese','Marshallese','Mauritanian','Mauritian','Mexican','Micronesian','Moldovan','Monégasque','Mongolian','Montenegrin','Moroccan','Mozambican','Myanmar','Namibian','Nauruan','Nepalese','New Zealander','Nicaraguan','Nigerian','Nigerien','North Korean','North Macedonian','Norwegian','Omani','Pakistani','Palauan','Palestinian','Panamanian','Papua New Guinean','Paraguayan','Peruvian','Polish','Portuguese','Qatari','Romanian','Russian','Rwandan','Saint Lucian','Salvadoran','Samoan','San Marinese','Saudi Arabian','Senegalese','Serbian','Seychellois','Sierra Leonean','Singaporean','Slovak','Slovenian','Solomon Islander','Somali','South African','South Korean','South Sudanese','Spanish','Sri Lankan','Sudanese','Surinamese','Swedish','Swiss','Syrian','Taiwanese','Tajik','Tanzanian','Thai','Timorese','Togolese','Tongan','Trinidadian and Tobagonian','Tunisian','Turkish','Turkmen','Tuvaluan','Ugandan','Ukrainian','Uruguayan','Uzbek','Vanuatuan','Vatican','Venezuelan','Vietnamese','Yemeni','Zambian','Zimbabwean'
] as const;

export default function NationalityCombobox({value,onChange,placeholder='Search nationality...',required=false}:{value:string;onChange:(value:string)=>void;placeholder?:string;required?:boolean}){
 const [open,setOpen]=useState(false); const [query,setQuery]=useState(value); const root=useRef<HTMLDivElement>(null);
 useEffect(()=>setQuery(value),[value]);
 useEffect(()=>{const close=(e:MouseEvent)=>{if(root.current&&!root.current.contains(e.target as Node))setOpen(false)};document.addEventListener('mousedown',close);return()=>document.removeEventListener('mousedown',close)},[]);
 const items=useMemo(()=>{const q=query.trim().toLowerCase();return NATIONALITIES.filter(x=>!q||x.toLowerCase().includes(q)).slice(0,60)},[query]);
 const select=(x:string)=>{onChange(x);setQuery(x);setOpen(false)};
 return <div className={styles.root} ref={root}><div className={styles.control}><input value={query} required={required} placeholder={placeholder} autoComplete="off" onFocus={()=>setOpen(true)} onChange={e=>{setQuery(e.target.value);onChange('');setOpen(true)}} onKeyDown={e=>{if(e.key==='Escape')setOpen(false);if(e.key==='Enter'&&open&&items.length){e.preventDefault();select(items[0])}}}/><button type="button" tabIndex={-1} aria-label="Open nationality list" onClick={()=>setOpen(v=>!v)}>⌄</button></div>{open&&<div className={styles.menu} role="listbox">{items.length?items.map(x=><button type="button" role="option" aria-selected={value===x} key={x} onMouseDown={e=>e.preventDefault()} onClick={()=>select(x)}>{x}</button>):<div className={styles.empty}>No matching nationality</div>}</div>}</div>
}
