import type { Locale } from './dictionaries';

export type ConnectCopy = {
  common: {
    member: string; refresh: string; refreshing: string; loading: string; retry: string; results: string;
    search: string; all: string; location: string; interests: string; language: string; age: string;
    profile: string; live: string; noPhoto: string; webSync: string;
  };
  friends: {
    title: string; subtitle: string; discover: string; requests: string; friends: string;
    searchPlaceholder: string; sharedInterests: string; sharedGoals: string; match: string;
    addFriend: string; requestSent: string; cancel: string; viewRequest: string; alreadyFriend: string;
    accept: string; decline: string; noDiscover: string; noRequests: string; noFriends: string;
    requestHint: string; friendHint: string; nationalityMatch: string; onlineFriend: string;
    localFriend: string; travelBuddy: string; languageExchange: string; activityPartner: string;
    today: string; weekend: string; traveling: string; unfriend: string; block: string;
    confirmUnfriend: string; confirmBlock: string;
  };
  love: {
    title: string; subtitle: string; recommended: string; likesYou: string; saved: string; matched: string;
    pass: string; save: string; savedState: string; like: string; matchNow: string; matchMessage: string;
    noRecommended: string; noLikes: string; noSaved: string; noMatched: string; relationshipGoal: string;
    lifestyle: string; interests: string; filterSummary: string; premiumTitle: string; premiumBody: string;
    premiumCta: string; likesRemaining: string; unlimited: string; zodiac: string; viewMore: string;
    drinking: string; smoking: string; exercise: string; pets: string; whyRecommended: string; compatibility: string;
    sharedInterests: string; onlineNow: string; lastActive: string; recommendation: string; chat: string;
  };
};

export const connectCopy: Record<Locale, ConnectCopy> = {
  th: {
    common: { member: 'MELO CONNECT', refresh: 'รีเฟรช', refreshing: 'กำลังรีเฟรช…', loading: 'กำลังโหลดข้อมูล…', retry: 'ลองใหม่', results: 'รายการ', search: 'ค้นหา', all: 'ทั้งหมด', location: 'สถานที่', interests: 'ความสนใจ', language: 'ภาษา', age: 'อายุ', profile: 'โปรไฟล์', live: 'ข้อมูลจากบัญชี Melo', noPhoto: 'ยังไม่มีรูป', webSync: 'ข้อมูลและสถานะเชื่อมกับบัญชี Melo เดียวกับในแอป' },
    friends: { title: 'หาเพื่อน', subtitle: 'ค้นหาคนที่มีไลฟ์สไตล์ ภาษา และความสนใจใกล้เคียงกัน แล้วส่งคำขอเป็นเพื่อนก่อนเริ่มคุย', discover: 'แนะนำ', requests: 'คำขอ', friends: 'เพื่อน', searchPlaceholder: 'ค้นหาชื่อ เมือง ประเทศ หรือความสนใจ', sharedInterests: 'ความสนใจที่ตรงกัน', sharedGoals: 'เป้าหมายเพื่อน', match: 'เข้ากันได้', addFriend: 'เพิ่มเพื่อน', requestSent: 'ส่งคำขอแล้ว', cancel: 'ยกเลิก', viewRequest: 'ดูคำขอ', alreadyFriend: 'เป็นเพื่อนแล้ว', accept: 'รับเป็นเพื่อน', decline: 'ปฏิเสธ', noDiscover: 'ยังไม่พบเพื่อนที่ตรงกัน', noRequests: 'ยังไม่มีคำขอเป็นเพื่อน', noFriends: 'ยังไม่มีเพื่อน', requestHint: 'เมื่อมีคนส่งคำขอเป็นเพื่อน คำขอจะแสดงที่นี่', friendHint: 'เมื่ออีกฝ่ายตอบรับแล้ว จึงจะเริ่มคุยกันได้เหมือนในแอป Melo', nationalityMatch: 'ตรงกับสัญชาติที่คุณสนใจ', onlineFriend: 'เพื่อนออนไลน์', localFriend: 'เพื่อนใกล้ตัว', travelBuddy: 'เพื่อนเที่ยว', languageExchange: 'แลกเปลี่ยนภาษา', activityPartner: 'เพื่อนทำกิจกรรม', today: 'ว่างวันนี้', weekend: 'ว่างสุดสัปดาห์', traveling: 'กำลังเดินทาง', unfriend: 'เลิกเป็นเพื่อน', block: 'บล็อก', confirmUnfriend: 'ต้องการเลิกเป็นเพื่อนกับ {name} หรือไม่?', confirmBlock: 'ต้องการบล็อก {name} หรือไม่? บุคคลนี้จะถูกซ่อนออกจากรายการเพื่อนและการค้นหา' },
    love: { title: 'หาคู่', subtitle: 'ค้นหาคนตามเพศ อายุ และสัญชาติที่คุณตั้งไว้ พร้อมสถานะถูกใจ บันทึก และจับคู่จากบัญชี Melo', recommended: 'แนะนำ', likesYou: 'ถูกใจคุณ', saved: 'บันทึก', matched: 'จับคู่', pass: 'ผ่าน', save: 'บันทึก', savedState: 'บันทึกแล้ว', like: 'สนใจ', matchNow: 'Match แล้ว!', matchMessage: 'คุณทั้งคู่กดสนใจกันแล้ว โปรไฟล์นี้ถูกย้ายไปที่แท็บจับคู่', noRecommended: 'ยังไม่มีโปรไฟล์ที่ตรงกับตัวกรองของคุณ', noLikes: 'ยังไม่มีคนที่ถูกใจคุณ', noSaved: 'ยังไม่มีโปรไฟล์ที่บันทึกไว้', noMatched: 'ยังไม่มีการจับคู่', relationshipGoal: 'ความสัมพันธ์ที่มองหา', lifestyle: 'ไลฟ์สไตล์', interests: 'ความสนใจ', filterSummary: 'ตัวกรองที่ใช้อยู่', premiumTitle: 'ดูว่าใครถูกใจคุณด้วย Premium', premiumBody: 'บัญชี Free จะไม่เปิดรายชื่อผู้ที่กดถูกใจคุณ ระบบเว็บยึดสิทธิ์แพ็กเกจเดียวกับในแอป', premiumCta: 'ดูบัญชีของฉัน', likesRemaining: 'Like ที่เหลือวันนี้', unlimited: 'ไม่จำกัด', zodiac: 'ราศี', viewMore: 'ดูข้อมูล', drinking: 'การดื่ม', smoking: 'การสูบบุหรี่', exercise: 'การออกกำลังกาย', pets: 'สัตว์เลี้ยง', whyRecommended: 'ทำไม Melo แนะนำคนนี้', compatibility: 'ความเข้ากันได้ของคุณ', sharedInterests: 'ความสนใจร่วมกัน', onlineNow: 'ออนไลน์', lastActive: 'ใช้งานล่าสุด', recommendation: 'แนะนำ', chat: 'แชท' },
  },
  en: {
    common: { member: 'MELO CONNECT', refresh: 'Refresh', refreshing: 'Refreshing…', loading: 'Loading…', retry: 'Try again', results: 'items', search: 'Search', all: 'All', location: 'Location', interests: 'Interests', language: 'Language', age: 'Age', profile: 'Profile', live: 'Live Melo account data', noPhoto: 'No photo', webSync: 'Data and relationship status stay in sync with the same Melo account used in the app.' },
    friends: { title: 'Find Friends', subtitle: 'Discover people with similar lifestyles, languages and interests. Send a friend request before chatting.', discover: 'Discover', requests: 'Requests', friends: 'Friends', searchPlaceholder: 'Search name, city, country or interest', sharedInterests: 'Shared interests', sharedGoals: 'Friend goals', match: 'match', addFriend: 'Add friend', requestSent: 'Request sent', cancel: 'Cancel', viewRequest: 'View request', alreadyFriend: 'Friends', accept: 'Accept', decline: 'Decline', noDiscover: 'No friend matches yet', noRequests: 'No friend requests yet', noFriends: 'No friends yet', requestHint: 'Incoming friend requests will appear here.', friendHint: 'Chat becomes available after the other person accepts, just like in the Melo app.', nationalityMatch: 'Matches your nationality preference', onlineFriend: 'Online friend', localFriend: 'Local friend', travelBuddy: 'Travel buddy', languageExchange: 'Language exchange', activityPartner: 'Activity partner', today: 'Free today', weekend: 'Free this weekend', traveling: 'Traveling', unfriend: 'Unfriend', block: 'Block', confirmUnfriend: 'Remove {name} from your friends?', confirmBlock: 'Block {name}? They will be hidden from your friend lists and discovery.' },
    love: { title: 'Love', subtitle: 'Discover people using your gender, age and nationality preferences, with likes, saves and matches synced from Melo.', recommended: 'Recommended', likesYou: 'Likes you', saved: 'Saved', matched: 'Matched', pass: 'Pass', save: 'Save', savedState: 'Saved', like: 'Interested', matchNow: 'It’s a match!', matchMessage: 'You both liked each other. This profile is now in your Matches tab.', noRecommended: 'No profiles currently match your filters.', noLikes: 'Nobody has liked you yet.', noSaved: 'No saved profiles yet.', noMatched: 'No matches yet.', relationshipGoal: 'Looking for', lifestyle: 'Lifestyle', interests: 'Interests', filterSummary: 'Active filters', premiumTitle: 'See who likes you with Premium', premiumBody: 'Free accounts cannot reveal incoming likes. Melo Web follows the same package entitlement as the app.', premiumCta: 'View my account', likesRemaining: 'Likes remaining today', unlimited: 'Unlimited', zodiac: 'Zodiac', viewMore: 'View details', drinking: 'Drinking', smoking: 'Smoking', exercise: 'Exercise', pets: 'Pets', whyRecommended: 'Why Melo recommends this person', compatibility: 'Your compatibility', sharedInterests: 'Shared interests', onlineNow: 'Online now', lastActive: 'Last active', recommendation: 'Recommended', chat: 'Chat' },
  },
  de: {
    common: { member: 'MELO CONNECT', refresh: 'Aktualisieren', refreshing: 'Aktualisieren…', loading: 'Wird geladen…', retry: 'Erneut versuchen', results: 'Einträge', search: 'Suchen', all: 'Alle', location: 'Ort', interests: 'Interessen', language: 'Sprache', age: 'Alter', profile: 'Profil', live: 'Live-Daten deines Melo-Kontos', noPhoto: 'Kein Foto', webSync: 'Daten und Beziehungsstatus werden mit demselben Melo-Konto wie in der App synchronisiert.' },
    friends: { title: 'Freunde finden', subtitle: 'Entdecke Menschen mit ähnlichem Lifestyle, Sprachen und Interessen. Vor dem Chat wird zuerst eine Freundschaftsanfrage gesendet.', discover: 'Entdecken', requests: 'Anfragen', friends: 'Freunde', searchPlaceholder: 'Name, Stadt, Land oder Interesse suchen', sharedInterests: 'Gemeinsame Interessen', sharedGoals: 'Freundschaftsziele', match: 'Match', addFriend: 'Freund hinzufügen', requestSent: 'Anfrage gesendet', cancel: 'Abbrechen', viewRequest: 'Anfrage ansehen', alreadyFriend: 'Freunde', accept: 'Annehmen', decline: 'Ablehnen', noDiscover: 'Noch keine passenden Freunde', noRequests: 'Noch keine Anfragen', noFriends: 'Noch keine Freunde', requestHint: 'Eingehende Freundschaftsanfragen erscheinen hier.', friendHint: 'Chat ist nach Annahme der Anfrage verfügbar – wie in der Melo-App.', nationalityMatch: 'Passt zur Nationalitätspräferenz', onlineFriend: 'Online-Freund', localFriend: 'Freund vor Ort', travelBuddy: 'Reisepartner', languageExchange: 'Sprachaustausch', activityPartner: 'Aktivitätspartner', today: 'Heute frei', weekend: 'Am Wochenende frei', traveling: 'Unterwegs', unfriend: 'Freundschaft beenden', block: 'Blockieren', confirmUnfriend: 'Freundschaft mit {name} beenden?', confirmBlock: '{name} blockieren? Die Person wird aus Freundeslisten und Empfehlungen ausgeblendet.' },
    love: { title: 'Love', subtitle: 'Entdecke Personen nach deinen Geschlechts-, Alters- und Nationalitätsfiltern. Likes, Favoriten und Matches sind mit Melo synchronisiert.', recommended: 'Empfohlen', likesYou: 'Mag dich', saved: 'Gespeichert', matched: 'Matches', pass: 'Weiter', save: 'Speichern', savedState: 'Gespeichert', like: 'Interessiert', matchNow: 'Match!', matchMessage: 'Ihr habt euch beide geliked. Das Profil ist jetzt unter Matches.', noRecommended: 'Keine Profile entsprechen derzeit deinen Filtern.', noLikes: 'Noch keine eingehenden Likes.', noSaved: 'Noch keine gespeicherten Profile.', noMatched: 'Noch keine Matches.', relationshipGoal: 'Gesucht', lifestyle: 'Lifestyle', interests: 'Interessen', filterSummary: 'Aktive Filter', premiumTitle: 'Sieh mit Premium, wer dich mag', premiumBody: 'Free-Konten können eingehende Likes nicht anzeigen. Melo Web verwendet dieselben Paketberechtigungen wie die App.', premiumCta: 'Mein Konto', likesRemaining: 'Verbleibende Likes heute', unlimited: 'Unbegrenzt', zodiac: 'Sternzeichen', viewMore: 'Details', drinking: 'Alkohol', smoking: 'Rauchen', exercise: 'Sport', pets: 'Haustiere', whyRecommended: 'Warum Melo diese Person empfiehlt', compatibility: 'Eure Kompatibilität', sharedInterests: 'Gemeinsame Interessen', onlineNow: 'Online', lastActive: 'Zuletzt aktiv', recommendation: 'Empfohlen', chat: 'Chat' },
  },
  zh: {
    common: { member: 'MELO CONNECT', refresh: '刷新', refreshing: '正在刷新…', loading: '正在加载…', retry: '重试', results: '条', search: '搜索', all: '全部', location: '地点', interests: '兴趣', language: '语言', age: '年龄', profile: '个人资料', live: 'Melo 账户实时数据', noPhoto: '暂无照片', webSync: '数据与关系状态会和 App 中的同一个 Melo 账户保持同步。' },
    friends: { title: '找朋友', subtitle: '发现生活方式、语言和兴趣相近的人。先发送好友请求，对方接受后才能聊天。', discover: '推荐', requests: '请求', friends: '好友', searchPlaceholder: '搜索姓名、城市、国家或兴趣', sharedInterests: '共同兴趣', sharedGoals: '交友目标', match: '匹配', addFriend: '添加好友', requestSent: '已发送请求', cancel: '取消', viewRequest: '查看请求', alreadyFriend: '已是好友', accept: '接受', decline: '拒绝', noDiscover: '暂时没有合适的好友推荐', noRequests: '暂时没有好友请求', noFriends: '暂时没有好友', requestHint: '收到的好友请求会显示在这里。', friendHint: '对方接受后即可开始聊天，与 Melo App 的流程一致。', nationalityMatch: '符合你的国籍偏好', onlineFriend: '线上好友', localFriend: '本地好友', travelBuddy: '旅行伙伴', languageExchange: '语言交换', activityPartner: '活动伙伴', today: '今天有空', weekend: '周末有空', traveling: '旅行中', unfriend: '解除好友', block: '屏蔽', confirmUnfriend: '要解除与 {name} 的好友关系吗？', confirmBlock: '要屏蔽 {name} 吗？对方将从好友列表和推荐中隐藏。' },
    love: { title: '恋爱', subtitle: '按你设置的性别、年龄和国籍筛选推荐，喜欢、收藏和匹配状态与 Melo 同步。', recommended: '推荐', likesYou: '喜欢你', saved: '收藏', matched: '匹配', pass: '跳过', save: '收藏', savedState: '已收藏', like: '感兴趣', matchNow: '匹配成功！', matchMessage: '你们互相喜欢，资料已移到“匹配”标签。', noRecommended: '目前没有符合筛选条件的资料。', noLikes: '目前还没有人喜欢你。', noSaved: '还没有收藏的资料。', noMatched: '还没有匹配。', relationshipGoal: '寻找关系', lifestyle: '生活方式', interests: '兴趣', filterSummary: '当前筛选', premiumTitle: '升级 Premium 查看谁喜欢你', premiumBody: '免费账户不能查看收到的喜欢。Melo Web 使用与 App 相同的套餐权限。', premiumCta: '查看我的账户', likesRemaining: '今日剩余喜欢次数', unlimited: '不限', zodiac: '星座', viewMore: '查看详情', drinking: '饮酒', smoking: '吸烟', exercise: '运动', pets: '宠物', whyRecommended: '为什么 Melo 推荐这个人', compatibility: '你们的契合度', sharedInterests: '共同兴趣', onlineNow: '在线', lastActive: '最近活跃', recommendation: '推荐', chat: '聊天' },
  },
  ja: {
    common: { member: 'MELO CONNECT', refresh: '更新', refreshing: '更新中…', loading: '読み込み中…', retry: '再試行', results: '件', search: '検索', all: 'すべて', location: '場所', interests: '興味', language: '言語', age: '年齢', profile: 'プロフィール', live: 'Meloアカウントのライブデータ', noPhoto: '写真なし', webSync: 'データと関係ステータスはアプリと同じMeloアカウントで同期されます。' },
    friends: { title: '友だちを探す', subtitle: 'ライフスタイル、言語、興味が近い人を見つけます。チャット前に友だち申請と承認が必要です。', discover: 'おすすめ', requests: '申請', friends: '友だち', searchPlaceholder: '名前・都市・国・興味で検索', sharedInterests: '共通の興味', sharedGoals: '友だちの目的', match: 'マッチ', addFriend: '友だち追加', requestSent: '申請済み', cancel: 'キャンセル', viewRequest: '申請を見る', alreadyFriend: '友だち', accept: '承認', decline: '拒否', noDiscover: '現在おすすめの友だちはいません', noRequests: '友だち申請はありません', noFriends: 'まだ友だちはいません', requestHint: '受信した友だち申請はここに表示されます。', friendHint: '相手が承認すると、Meloアプリと同じようにチャットできます。', nationalityMatch: '国籍の希望に一致', onlineFriend: 'オンライン友だち', localFriend: '近くの友だち', travelBuddy: '旅仲間', languageExchange: '言語交換', activityPartner: 'アクティビティ仲間', today: '今日空いている', weekend: '週末空いている', traveling: '旅行中', unfriend: '友だち解除', block: 'ブロック', confirmUnfriend: '{name} との友だち関係を解除しますか？', confirmBlock: '{name} をブロックしますか？友だち一覧やおすすめに表示されなくなります。' },
    love: { title: '恋愛', subtitle: '設定した性別・年齢・国籍で相手を探し、いいね・保存・マッチをMeloアカウントと同期します。', recommended: 'おすすめ', likesYou: 'あなたへのいいね', saved: '保存', matched: 'マッチ', pass: 'スキップ', save: '保存', savedState: '保存済み', like: '興味あり', matchNow: 'マッチしました！', matchMessage: 'お互いにいいねしました。このプロフィールはマッチタブに移動しました。', noRecommended: '現在フィルターに一致するプロフィールはありません。', noLikes: 'まだあなたへのいいねはありません。', noSaved: '保存したプロフィールはありません。', noMatched: 'まだマッチはありません。', relationshipGoal: '探している関係', lifestyle: 'ライフスタイル', interests: '興味', filterSummary: '現在のフィルター', premiumTitle: 'Premiumで「あなたへのいいね」を確認', premiumBody: 'Freeアカウントでは受信いいねを表示できません。Melo Webはアプリと同じパッケージ権限を使用します。', premiumCta: 'アカウントを見る', likesRemaining: '今日の残りLike', unlimited: '無制限', zodiac: '星座', viewMore: '詳細を見る', drinking: '飲酒', smoking: '喫煙', exercise: '運動', pets: 'ペット', whyRecommended: 'Meloがおすすめする理由', compatibility: 'あなたとの相性', sharedInterests: '共通の興味', onlineNow: 'オンライン', lastActive: '最終アクティブ', recommendation: 'おすすめ', chat: 'チャット' },
  },
  ko: {
    common: { member: 'MELO CONNECT', refresh: '새로고침', refreshing: '새로고침 중…', loading: '불러오는 중…', retry: '다시 시도', results: '개', search: '검색', all: '전체', location: '위치', interests: '관심사', language: '언어', age: '나이', profile: '프로필', live: 'Melo 계정 실시간 데이터', noPhoto: '사진 없음', webSync: '데이터와 관계 상태는 앱과 동일한 Melo 계정으로 동기화됩니다.' },
    friends: { title: '친구 찾기', subtitle: '라이프스타일, 언어, 관심사가 비슷한 사람을 찾아보세요. 채팅 전 친구 요청과 수락이 필요합니다.', discover: '추천', requests: '요청', friends: '친구', searchPlaceholder: '이름, 도시, 국가 또는 관심사 검색', sharedInterests: '공통 관심사', sharedGoals: '친구 목표', match: '매치', addFriend: '친구 추가', requestSent: '요청 보냄', cancel: '취소', viewRequest: '요청 보기', alreadyFriend: '친구', accept: '수락', decline: '거절', noDiscover: '현재 추천 친구가 없습니다', noRequests: '친구 요청이 없습니다', noFriends: '아직 친구가 없습니다', requestHint: '받은 친구 요청이 여기에 표시됩니다.', friendHint: '상대가 수락하면 Melo 앱과 동일하게 채팅할 수 있습니다.', nationalityMatch: '선호 국적과 일치', onlineFriend: '온라인 친구', localFriend: '근처 친구', travelBuddy: '여행 친구', languageExchange: '언어 교환', activityPartner: '활동 친구', today: '오늘 시간 있음', weekend: '주말 시간 있음', traveling: '여행 중', unfriend: '친구 삭제', block: '차단', confirmUnfriend: '{name} 님과 친구 관계를 해제할까요?', confirmBlock: '{name} 님을 차단할까요? 친구 목록과 추천에서 숨겨집니다.' },
    love: { title: '연애', subtitle: '설정한 성별, 나이, 국적 조건으로 추천을 보고 좋아요·저장·매치 상태를 Melo와 동기화합니다.', recommended: '추천', likesYou: '나를 좋아함', saved: '저장', matched: '매치', pass: '넘기기', save: '저장', savedState: '저장됨', like: '관심', matchNow: '매치됐어요!', matchMessage: '서로 좋아요를 눌렀습니다. 이 프로필은 매치 탭으로 이동했습니다.', noRecommended: '현재 필터에 맞는 프로필이 없습니다.', noLikes: '아직 나를 좋아한 사람이 없습니다.', noSaved: '저장한 프로필이 없습니다.', noMatched: '아직 매치가 없습니다.', relationshipGoal: '원하는 관계', lifestyle: '라이프스타일', interests: '관심사', filterSummary: '현재 필터', premiumTitle: 'Premium으로 누가 나를 좋아하는지 확인', premiumBody: 'Free 계정은 받은 좋아요를 볼 수 없습니다. Melo Web은 앱과 동일한 패키지 권한을 사용합니다.', premiumCta: '내 계정 보기', likesRemaining: '오늘 남은 Like', unlimited: '무제한', zodiac: '별자리', viewMore: '상세 보기', drinking: '음주', smoking: '흡연', exercise: '운동', pets: '반려동물', whyRecommended: 'Melo가 이 사람을 추천하는 이유', compatibility: '두 사람의 궁합', sharedInterests: '공통 관심사', onlineNow: '온라인', lastActive: '최근 활동', recommendation: '추천', chat: '채팅' },
  },
};
