'use client';
import { useEffect, useRef, useState } from 'react';
import { useRouter } from 'next/navigation';
import { useLocale } from '@/components/SiteProviders';
import { arrayOf, loadOwnProfile, profilePhotoUrl, updateOwnProfile, uploadProfilePhotoWeb, type ProfileRow } from '@/components/profile/profileWebData';
import styles from './ProfileOnboardingExperience.module.css';
import NationalityCombobox from '@/components/NationalityCombobox';

type L='th'|'en'|'de'; type Life=Record<string,string[]>;
const C={
th:{brand:'MELO CHAT LITE',title:'ตั้งค่าโปรไฟล์ของคุณ',sub:'อีกเพียงไม่กี่ขั้นตอน เพื่อให้ Melo แนะนำคนที่เหมาะกับคุณได้ดีขึ้น',personal:'ข้อมูลส่วนตัว',matching:'กำลังมองหา',lifestyle:'ไลฟ์สไตล์',first:'ชื่อ',last:'นามสกุล',ownGender:'เพศ',birthDate:'วันเดือนปีเกิด',mainPhoto:'รูปโปรไฟล์',mainPhotoDesc:'รูปโปรไฟล์หลัก 1 รูป (จำเป็น)',gallery:'Profile Photos Gallery',galleryDesc:'เพิ่มได้สูงสุด 6 รูป (ไม่บังคับ)',addPhoto:'เพิ่มรูป',replacePhoto:'เปลี่ยนรูป',height:'ส่วนสูง (ซม.)',nationality:'สัญชาติ',nationalitySearch:'พิมพ์เพื่อค้นหาสัญชาติ...',education:'การศึกษา',status:'สถานะความสัมพันธ์',gender:'เพศที่สนใจ',relation:'ความสัมพันธ์ที่กำลังมองหา',orientation:'รสนิยมทางเพศ',pets:'สัตว์เลี้ยง',drink:'การดื่ม',smoke:'การสูบบุหรี่',exercise:'การออกกำลังกาย',social:'บุคลิกทางสังคม',interests:'ความสนใจ',next:'ถัดไป',back:'ย้อนกลับ',finish:'บันทึกและเริ่มใช้งาน',saving:'กำลังบันทึก...',required:'กรุณากรอกข้อมูลที่จำเป็นให้ครบ',age20:'ผู้สมัครต้องมีอายุครบ 20 ปีบริบูรณ์ขึ้นไป'},
en:{brand:'MELO CHAT LITE',title:'Set up your profile',sub:'A few quick steps help Melo recommend more relevant people for you.',personal:'Personal details',matching:'Looking for',lifestyle:'Lifestyle',first:'First name',last:'Last name',ownGender:'Gender',birthDate:'Date of birth',mainPhoto:'Profile photo',mainPhotoDesc:'1 main profile photo (required)',gallery:'Profile Photos Gallery',galleryDesc:'Add up to 6 photos (optional)',addPhoto:'Add photo',replacePhoto:'Replace photo',height:'Height (cm)',nationality:'Nationality',nationalitySearch:'Search nationality...',education:'Education',status:'Relationship status',gender:'Interested in',relation:'Relationship you are looking for',orientation:'Sexual orientation',pets:'Pets',drink:'Drinking',smoke:'Smoking',exercise:'Exercise',social:'Social style',interests:'Interests',next:'Next',back:'Back',finish:'Save and start',saving:'Saving...',required:'Please complete the required information.',age20:'You must be at least 20 years old to register.'},
de:{brand:'MELO CHAT LITE',title:'Profil einrichten',sub:'Ein paar kurze Schritte helfen Melo, passendere Personen vorzuschlagen.',personal:'Persönliche Angaben',matching:'Ich suche',lifestyle:'Lebensstil',first:'Vorname',last:'Nachname',ownGender:'Geschlecht',birthDate:'Geburtsdatum',mainPhoto:'Profilbild',mainPhotoDesc:'1 Hauptprofilbild (erforderlich)',gallery:'Profil-Fotogalerie',galleryDesc:'Bis zu 6 Fotos hinzufügen (optional)',addPhoto:'Foto hinzufügen',replacePhoto:'Foto ersetzen',height:'Größe (cm)',nationality:'Nationalität',nationalitySearch:'Nationalität suchen...',education:'Ausbildung',status:'Beziehungsstatus',gender:'Interessiert an',relation:'Gesuchte Beziehung',orientation:'Sexuelle Orientierung',pets:'Haustiere',drink:'Alkohol',smoke:'Rauchen',exercise:'Sport',social:'Sozialer Typ',interests:'Interessen',next:'Weiter',back:'Zurück',finish:'Speichern und starten',saving:'Speichern...',required:'Bitte fülle die erforderlichen Angaben aus.',age20:'Du musst mindestens 20 Jahre alt sein, um dich zu registrieren.'}} as const;
const O={
education:{th:['มัธยมศึกษา','ปวช. / ปวส.','ปริญญาตรี','ปริญญาโท','ปริญญาเอก','อื่น ๆ'],en:['High school','Vocational / Diploma',"Bachelor's degree","Master's degree",'Doctorate','Other'],de:['Schulabschluss','Berufsausbildung / Diplom','Bachelor','Master','Promotion','Andere']},
status:{th:['โสด','เคยแต่งงาน','หย่าร้าง','หม้าย'],en:['Single','Previously married','Divorced','Widowed'],de:['Single','Früher verheiratet','Geschieden','Verwitwet']},
ownGender:{th:['ชาย','หญิง','นอนไบนารี','อื่น ๆ','ไม่ต้องการระบุ'],en:['Man','Woman','Non-binary','Other','Prefer not to say'],de:['Mann','Frau','Nicht-binär','Andere','Keine Angabe']},gender:{th:['เพศชาย','เพศหญิง','LGBTQ+'],en:['Men','Women','LGBTQ+'],de:['Männer','Frauen','LGBTQ+']},relation:{th:['ความสัมพันธ์จริงจัง','คบหาดูใจ','เพื่อน','พูดคุยทำความรู้จัก','ยังไม่แน่ใจ'],en:['Long-term relationship','Dating','Friendship','Getting to know someone','Not sure yet'],de:['Feste Beziehung','Dating','Freundschaft','Kennenlernen','Noch unsicher']},orientation:{th:['Straight','Gay','Lesbian','Bisexual','Pansexual','Asexual','อื่น ๆ','ไม่ต้องการระบุ'],en:['Straight','Gay','Lesbian','Bisexual','Pansexual','Asexual','Other','Prefer not to say'],de:['Heterosexuell','Schwul','Lesbisch','Bisexuell','Pansexuell','Asexuell','Andere','Keine Angabe']},pets:{th:['สุนัข','แมว','นก','ปลา','สัตว์เลี้ยงอื่น ๆ','ไม่มีสัตว์เลี้ยง'],en:['Dogs','Cats','Birds','Fish','Other pets','No pets'],de:['Hunde','Katzen','Vögel','Fische','Andere Haustiere','Keine Haustiere']},drink:{th:['ไม่ดื่ม','ดื่มเล็กน้อย','ดื่มตามโอกาสพิเศษ','ดื่มช่วงวันหยุด','ดื่มเป็นประจำ'],en:['Never','Rarely','Special occasions','Weekends','Regularly'],de:['Nie','Selten','Besondere Anlässe','Am Wochenende','Regelmäßig']},smoke:{th:['ไม่สูบ','สูบบางครั้ง','สูบเป็นประจำ','กำลังเลิก'],en:['Never','Sometimes','Regularly','Quitting'],de:['Nie','Manchmal','Regelmäßig','Höre gerade auf']},exercise:{th:['ไม่ค่อยออก','สัปดาห์ละ 1–2 ครั้ง','สัปดาห์ละ 3–4 ครั้ง','เกือบทุกวัน'],en:['Rarely','1–2 times/week','3–4 times/week','Almost daily'],de:['Selten','1–2× pro Woche','3–4× pro Woche','Fast täglich']},social:{th:['Introvert','Ambivert','Extrovert'],en:['Introvert','Ambivert','Extrovert'],de:['Introvertiert','Ambivertiert','Extrovertiert']},interests:{th:['Coffee','Travel','Fitness','Foodie','Music','Pets','Art','Beach'],en:['Coffee','Travel','Fitness','Foodie','Music','Pets','Art','Beach'],de:['Kaffee','Reisen','Fitness','Foodie','Musik','Haustiere','Kunst','Strand']}} as const;
function Chips({items,value,set,multi=true}:{items:readonly string[],value:string[],set:(x:string[])=>void,multi?:boolean}){return <div className={styles.chips}>{items.map(x=><button type="button" key={x} data-on={value.includes(x)} onClick={()=>set(multi?(value.includes(x)?value.filter(v=>v!==x):[...value,x]):[x])}>{x}</button>)}</div>}
export default function ProfileOnboardingExperience(){const router=useRouter();const {locale,setLocale,theme,toggleTheme}=useLocale();const l=(locale in C?locale:'en') as L,t=C[l];const [step,setStep]=useState(1),[uid,setUid]=useState(''),[busy,setBusy]=useState(true),[err,setErr]=useState('');const [f,setF]=useState({first_name:'',last_name:'',date_of_birth:'',height_cm:'',nationality:'',education:'',marital_status:'',gender:''});const [profile,setProfile]=useState<ProfileRow>({});const [uploading,setUploading]=useState<number|null>(null);const photoInputs=useRef<(HTMLInputElement|null)[]>([]);const [gender,setGender]=useState<string[]>([]),[rel,setRel]=useState<string[]>([]),[ori,setOri]=useState<string[]>([]),[life,setLife]=useState<Life>({});
useEffect(()=>{void(async()=>{const r=await loadOwnProfile();if(!r.data){router.replace('/login');return}const p=r.data.profile;if(p.onboarding_completed){router.replace('/account');return}setUid(r.data.userId);setProfile(p);setStep(Math.max(1,Math.min(3,Number(p.onboarding_step||1))));setF({first_name:String(p.first_name||''),last_name:String(p.last_name||''),date_of_birth:String(p.date_of_birth||''),height_cm:p.height_cm?String(p.height_cm):'',nationality:String(p.nationality||''),education:String(p.education||''),marital_status:String(p.marital_status||''),gender:String(p.gender||'')});const look=arrayOf(p.looking_for);setGender(look.filter((x:string)=>(O.gender[l] as readonly string[]).includes(x)));setRel(look.filter((x:string)=>(O.relation[l] as readonly string[]).includes(x)));setOri(arrayOf(p.sexual_orientations));setLife(p.lifestyle_preferences&&typeof p.lifestyle_preferences==='object'?p.lifestyle_preferences:{});setBusy(false)})()},[l,router]);
const uploadPhoto=async(slotIndex:number,file?:File)=>{if(!file)return;setUploading(slotIndex);setErr('');try{const r=await uploadProfilePhotoWeb({file,slotIndex,currentPaths:arrayOf(profile.photo_paths)});setProfile(x=>({...x,photo_paths:r.paths}));}catch(e){setErr(e instanceof Error?e.message:String(e));}finally{setUploading(null)}};
const isAtLeast20=(value:string)=>{if(!value)return false;const birth=new Date(`${value}T00:00:00`);if(Number.isNaN(birth.getTime()))return false;const today=new Date();const twentieth=new Date(birth.getFullYear()+20,birth.getMonth(),birth.getDate());return twentieth<=today};
const maxBirthDate=(()=>{const d=new Date();d.setFullYear(d.getFullYear()-20);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`})();
const saveStep=async(next:number,complete=false)=>{setErr('');if(step===1&&(!profilePhotoUrl(profile,0)||!f.first_name.trim()||!f.last_name.trim()||!f.gender||!f.date_of_birth||!f.height_cm||!f.nationality.trim()||!f.education||!f.marital_status)){setErr(t.required);return}if(step===1&&!isAtLeast20(f.date_of_birth)){setErr(t.age20);return}if(step===2&&(!gender.length||!rel.length||!ori.length)){setErr(t.required);return}if(step===3&&(!life.pets?.length||!life.drink?.length||!life.smoke?.length||!life.exercise?.length||!life.social?.length||!life.interests?.length)){setErr(t.required);return}setBusy(true);const payload:any={onboarding_step:next};if(step===1)Object.assign(payload,{...f,height_cm:Number(f.height_cm)});if(step===2)Object.assign(payload,{looking_for:[...gender,...rel],sexual_orientations:ori});if(step===3)Object.assign(payload,{lifestyle_preferences:life,onboarding_completed:true,onboarding_step:3});const r=await updateOwnProfile(uid,payload);setBusy(false);if(r.error){setErr(r.error);return}if(complete){router.replace('/account');router.refresh()}else setStep(next)};
if(busy&&!uid)return <main className={styles.page}><div className={styles.loading}>Melo Chat…</div></main>;
return <main className={styles.page}><section className={styles.shell}><div className={styles.topbar}><div className={styles.brand}>{t.brand}</div><div className={styles.controls}><label className={styles.language}><span aria-hidden="true">🌐</span><select aria-label={l==='th'?'ภาษาแอป':l==='de'?'App-Sprache':'App language'} value={l} onChange={e=>setLocale(e.target.value as L)}><option value="th">ไทย</option><option value="en">English</option><option value="de">Deutsch</option></select></label><button type="button" className={styles.theme} onClick={toggleTheme} aria-label={theme==='dark'?(l==='th'?'เปลี่ยนเป็นโหมดสว่าง':l==='de'?'Helles Design':'Switch to light mode'):(l==='th'?'เปลี่ยนเป็นโหมดมืด':l==='de'?'Dunkles Design':'Switch to dark mode')} title={theme==='dark'?(l==='th'?'โหมดสว่าง':l==='de'?'Hell':'Light'):(l==='th'?'โหมดมืด':l==='de'?'Dunkel':'Dark')}>{theme==='dark'?'☀️':'🌙'}</button></div></div><h1>{t.title}</h1><p className={styles.sub}>{t.sub}</p><div className={styles.progress}>{[t.personal,t.matching,t.lifestyle].map((x,i)=><div key={x} data-active={step>=i+1}><span>{i+1}</span><b>{x}</b></div>)}</div><div className={styles.card}><h2>{step===1?t.personal:step===2?t.matching:t.lifestyle}</h2>{err&&<div className={styles.error}>{err}</div>}
{step===1&&<><div className={styles.photoSetup}><div><strong>{t.mainPhoto} *</strong><small>{t.mainPhotoDesc}</small><div className={styles.mainPhoto}>{profilePhotoUrl(profile,0)?<img src={profilePhotoUrl(profile,0)} alt=""/>:<span>＋</span>}<input ref={el=>{photoInputs.current[0]=el}} type="file" accept="image/*" hidden onChange={e=>{void uploadPhoto(0,e.target.files?.[0]);e.currentTarget.value=''}}/><button type="button" disabled={uploading===0} onClick={()=>photoInputs.current[0]?.click()}>{profilePhotoUrl(profile,0)?t.replacePhoto:t.addPhoto}</button></div></div><div className={styles.gallerySetup}><strong>{t.gallery}</strong><small>{t.galleryDesc}</small><div className={styles.galleryRow}>{Array.from({length:6}).map((_,i)=>{const url=profilePhotoUrl(profile,i+1);return <div className={styles.galleryPhoto} key={i}>{url?<img src={url} alt=""/>:<span>＋</span>}<input ref={el=>{photoInputs.current[i+1]=el}} type="file" accept="image/*" hidden onChange={e=>{void uploadPhoto(i+1,e.target.files?.[0]);e.currentTarget.value=''}}/><button type="button" disabled={uploading===i+1} onClick={()=>photoInputs.current[i+1]?.click()}>{url?t.replacePhoto:t.addPhoto}</button></div>})}</div></div></div><div className={styles.grid}><label><span>{t.first} *</span><input value={f.first_name} onChange={e=>setF({...f,first_name:e.target.value})}/></label><label><span>{t.last} *</span><input value={f.last_name} onChange={e=>setF({...f,last_name:e.target.value})}/></label><label><span>{t.ownGender} *</span><select value={f.gender} onChange={e=>setF({...f,gender:e.target.value})}><option value="">—</option>{O.ownGender[l].map(x=><option key={x} value={x}>{x}</option>)}</select></label><label><span>{t.birthDate} *</span><input type="date" max={maxBirthDate} value={f.date_of_birth} onChange={e=>setF({...f,date_of_birth:e.target.value})}/></label><label><span>{t.height} *</span><input type="number" min="100" max="250" value={f.height_cm} onChange={e=>setF({...f,height_cm:e.target.value})}/></label><label><span>{t.nationality} *</span><NationalityCombobox value={f.nationality} onChange={value=>setF({...f,nationality:value})} placeholder={t.nationalitySearch} required/></label><label><span>{t.education} *</span><select value={f.education} onChange={e=>setF({...f,education:e.target.value})}><option value="">—</option>{O.education[l].map(x=><option key={x}>{x}</option>)}</select></label><label><span>{t.status} *</span><select value={f.marital_status} onChange={e=>setF({...f,marital_status:e.target.value})}><option value="">—</option>{O.status[l].map((x,i)=><option key={x} value={['single','previously_married','divorced','widowed'][i]}>{x}</option>)}</select></label></div></>}
{step===2&&<div className={styles.sections}><div><h3>{t.gender} *</h3><Chips items={O.gender[l]} value={gender} set={setGender}/></div><div><h3>{t.relation} *</h3><Chips items={O.relation[l]} value={rel} set={setRel}/></div><div><h3>{t.orientation} *</h3><Chips items={O.orientation[l]} value={ori} set={setOri}/></div></div>}
{step===3&&<div className={styles.sections}>{([['pets','pets',true],['drink','drink',false],['smoke','smoke',false],['exercise','exercise',false],['social','social',false],['interests','interests',true]] as const).map(([k,label,multi])=><div key={k}><h3>{t[label]} *</h3><Chips items={O[k][l]} value={life[k]||[]} set={v=>setLife({...life,[k]:v})} multi={multi}/></div>)}</div>}
<div className={styles.actions}>{step>1?<button className={styles.back} disabled={busy} onClick={()=>setStep(step-1)}>{t.back}</button>:<span/>}<button className={styles.next} disabled={busy} onClick={()=>void saveStep(step===3?3:step+1,step===3)}>{busy?t.saving:step===3?t.finish:t.next}</button></div></div></section></main>}
