'use client';

import { useEffect, useMemo, useState } from 'react';
import { useLocale } from '@/components/SiteProviders';
import { createSignedStorageUrl, publicStorageUrl, rpcRequest } from '@/lib/supabase/browser';
import styles from './AdminVerificationReview.module.css';

type Row=Record<string,any>;
type Item={id:string;userId:string;email:string;name:string;country:string;status:string;submittedAt:string;first:string;last:string;documentType:string;documentNumber:string;identityPath:string;selfiePath:string;notes:string;identityUrl?:string;selfieUrl?:string;avatarUrl?:string};
const C={
 th:{title:'คำขอยืนยันตัวตน',sub:'เลือกรายชื่อเพื่อดูข้อมูลและเอกสารที่ส่งเข้ามา',search:'ค้นหาชื่อ อีเมล หรือประเทศ',pending:'รอตรวจสอบ',empty:'ยังไม่มีคำขอยืนยันตัวตน',details:'ข้อมูลบนเอกสาร',first:'ชื่อจริง (ภาษาอังกฤษ)',last:'นามสกุล (ภาษาอังกฤษ)',type:'ประเภทเอกสาร',number:'เลขที่เอกสาร',document:'เอกสารยืนยันตัวตน',selfie:'ภาพเซลฟี่',approve:'อนุมัติ',reject:'รีเจค',rejectTitle:'เหตุผลที่รีเจค',rejectHint:'ระบุสิ่งที่ผู้ใช้ต้องแก้ไขก่อนส่งใหม่',cancel:'ยกเลิก',sendReject:'ส่งกลับให้แก้ไข',refresh:'รีเฟรช',noFile:'ไม่พบไฟล์',id:'บัตรประจำตัวประชาชน',passport:'หนังสือเดินทาง',driver:'ใบขับขี่',confirmApprove:'ยืนยันอนุมัติคำขอนี้หรือไม่?',approved:'อนุมัติเรียบร้อยแล้ว',rejected:'ส่งเหตุผลกลับไปยังผู้ใช้แล้ว',reasonRequired:'กรุณาระบุเหตุผลที่รีเจค',confirmTitle:'ยืนยันการอนุมัติเอกสาร',confirmBody:'คุณต้องการอนุมัติคำขอยืนยันตัวตนของสมาชิกคนนี้หรือไม่?',confirmAction:'ยืนยันอนุมัติ'},
 en:{title:'Identity verification requests',sub:'Select a user to review the submitted details and documents.',search:'Search name, email or country',pending:'Pending review',empty:'No verification requests',details:'Document details',first:'Legal first name (English)',last:'Legal last name (English)',type:'Document type',number:'Document number',document:'Identity document',selfie:'Selfie photo',approve:'Approve',reject:'Reject',rejectTitle:'Reason for rejection',rejectHint:'Tell the user what must be corrected before resubmitting.',cancel:'Cancel',sendReject:'Send back for changes',refresh:'Refresh',noFile:'File unavailable',id:'National ID card',passport:'Passport',driver:'Driver license',confirmApprove:'Approve this verification request?',approved:'Verification approved.',rejected:'The rejection reason was sent to the user.',reasonRequired:'Please enter a rejection reason.',confirmTitle:'Confirm verification approval',confirmBody:'Do you want to approve this member’s identity verification request?',confirmAction:'Approve verification'},
 de:{title:'Anfragen zur Identitätsprüfung',sub:'Wähle einen Nutzer aus, um Daten und Dokumente zu prüfen.',search:'Name, E-Mail oder Land suchen',pending:'Wird geprüft',empty:'Keine Verifizierungsanfragen',details:'Dokumentdaten',first:'Vorname laut Dokument (Englisch)',last:'Nachname laut Dokument (Englisch)',type:'Dokumenttyp',number:'Dokumentnummer',document:'Identitätsdokument',selfie:'Selfie-Foto',approve:'Genehmigen',reject:'Ablehnen',rejectTitle:'Grund der Ablehnung',rejectHint:'Teile dem Nutzer mit, was vor dem erneuten Senden korrigiert werden muss.',cancel:'Abbrechen',sendReject:'Zur Korrektur zurücksenden',refresh:'Aktualisieren',noFile:'Datei nicht verfügbar',id:'Personalausweis',passport:'Reisepass',driver:'Führerschein',confirmApprove:'Diese Verifizierungsanfrage genehmigen?',approved:'Verifizierung genehmigt.',rejected:'Der Ablehnungsgrund wurde an den Nutzer gesendet.',reasonRequired:'Bitte gib einen Ablehnungsgrund ein.',confirmTitle:'Verifizierung bestätigen',confirmBody:'Möchtest du die Identitätsprüfung dieses Mitglieds genehmigen?',confirmAction:'Verifizierung genehmigen'}
} as const;
function rows(v:unknown):Row[]{return Array.isArray(v)?v as Row[]:v&&typeof v==='object'?[v as Row]:[]}
function mapRow(r:Row):Item{const first=String(r.legal_first_name_en||'');const last=String(r.legal_last_name_en||'');return{id:String(r.id||''),userId:String(r.user_id||''),email:String(r.user_email||''),name:String(r.display_name||`${first} ${last}`.trim()||r.user_email||'Melo User'),country:String(r.country||r.nationality||'—'),status:String(r.status||'pending'),submittedAt:String(r.submitted_at||''),first,last,documentType:String(r.document_type||''),documentNumber:String(r.document_number||''),identityPath:String(r.identity_document_path||''),selfiePath:String(r.selfie_path||''),notes:String(r.reviewer_notes||'')}}
export default function AdminVerificationReview(){
 const {locale}=useLocale(); const t=C[locale==='th'?'th':locale==='de'?'de':'en'];
 const [items,setItems]=useState<Item[]>([]),[page,setPage]=useState(1),[selected,setSelected]=useState(''),[query,setQuery]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[rejectOpen,setRejectOpen]=useState(false),[approveOpen,setApproveOpen]=useState(false),[reason,setReason]=useState('');
 async function load(){setLoading(true);setError('');const r=await rpcRequest<Row[]>('get_admin_verification_queue',{p_status:'pending',p_limit:200});if(r.error){setError(r.error);setItems([]);setLoading(false);return}const base=rows(r.data).map(mapRow);const usersResult=await rpcRequest<Row[]|Row>('admin_center_list_users',{});const userRows=usersResult.error?[]:rows(usersResult.data);const avatars=new Map(userRows.map(u=>[String(u.user_id||''),String(u.avatar_url||'')]));const withUrls=await Promise.all(base.map(async x=>{const [a,b]=await Promise.all([x.identityPath?createSignedStorageUrl('verification-private',x.identityPath,1800):Promise.resolve({data:null,error:null}),x.selfiePath?createSignedStorageUrl('verification-private',x.selfiePath,1800):Promise.resolve({data:null,error:null})]);const rawAvatar=avatars.get(x.userId)||'';const avatarUrl=rawAvatar?( /^https?:\/\//i.test(rawAvatar)?rawAvatar:publicStorageUrl('profile-photos',rawAvatar) ):'';return{...x,identityUrl:a.data||'',selfieUrl:b.data||'',avatarUrl}}));setItems(withUrls);setSelected(s=>withUrls.some(x=>x.id===s)?s:(withUrls[0]?.id||''));setLoading(false)}
 useEffect(()=>{void load()},[]);
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return q?items.filter(x=>`${x.name} ${x.email} ${x.country}`.toLowerCase().includes(q)):items},[items,query]);
 useEffect(()=>setPage(1),[query]);
 const pages=Math.max(1,Math.ceil(filtered.length/10)); const safePage=Math.min(page,pages); const visible=filtered.slice((safePage-1)*10,safePage*10);
 const item=items.find(x=>x.id===selected)||null;
 const docType=(v:string)=>v==='passport'?t.passport:v==='driver_license'?t.driver:t.id;
 async function resolve(action:'approve'|'reject'){if(!item||busy)return;if(action==='reject'&&!reason.trim()){setError(t.reasonRequired);return}setBusy(true);setError('');setMessage('');const r=await rpcRequest('resolve_admin_verification_request',{p_request_id:item.id,p_action:action,p_note:action==='reject'?reason.trim():null});if(r.error)setError(r.error);else{setMessage(action==='approve'?t.approved:t.rejected);setRejectOpen(false);setApproveOpen(false);setReason('');await load()}setBusy(false)}
 return <div className={styles.review}>
  <aside className={styles.listPane}><div className={styles.listHead}><div><h2>{t.title}</h2><p>{t.sub}</p></div><span>{items.length}</span></div><div className={styles.search}>⌕<input value={query} onChange={e=>setQuery(e.target.value)} placeholder={t.search}/><button onClick={()=>void load()} title={t.refresh}>↻</button></div><div className={styles.people}>{loading?<div className={styles.empty}>…</div>:filtered.length?visible.map(x=><button key={x.id} className={x.id===selected?styles.personActive:styles.person} onClick={()=>setSelected(x.id)}><span className={styles.avatar}>{x.avatarUrl?<img src={x.avatarUrl} alt="" onError={e=>{e.currentTarget.style.display='none'}}/>:x.name.slice(0,1).toUpperCase()}</span><span className={styles.personText}><strong>{x.name}</strong><small>{x.country} · {x.email}</small><em>● {t.pending}</em></span><span className={styles.chev}>›</span></button>):<div className={styles.empty}>{t.empty}</div>}</div>{filtered.length>10?<div className={styles.pagination}><button disabled={safePage<=1} onClick={()=>setPage(safePage-1)}>‹</button><span>{safePage} / {pages}</span><button disabled={safePage>=pages} onClick={()=>setPage(safePage+1)}>›</button></div>:null}</aside>
  <section className={styles.detailPane}>{error?<div className={styles.error}>{error}</div>:null}{message?<div className={styles.success}>{message}</div>:null}{item?<><header className={styles.profileHead}><span className={styles.bigAvatar}>{item.avatarUrl?<img src={item.avatarUrl} alt="" onError={e=>{e.currentTarget.style.display='none'}}/>:item.name.slice(0,1).toUpperCase()}</span><div><h2>{item.name}</h2><p>{item.country} · {item.email}</p><span>● {t.pending}</span></div></header><div className={styles.infoCard}><h3>{t.details}</h3><div className={styles.infoGrid}><label><span>{t.first}</span><strong>{item.first||'—'}</strong></label><label><span>{t.last}</span><strong>{item.last||'—'}</strong></label><label><span>{t.type}</span><strong>{docType(item.documentType)}</strong></label><label><span>{t.number}</span><strong>{item.documentNumber||'—'}</strong></label></div></div><div className={styles.docs}><Doc title={t.document} url={item.identityUrl} empty={t.noFile}/><Doc title={t.selfie} url={item.selfieUrl} empty={t.noFile}/></div><div className={styles.actions}><button className={styles.reject} onClick={()=>setRejectOpen(true)} disabled={busy}>{t.reject}</button><button className={styles.approve} onClick={()=>setApproveOpen(true)} disabled={busy}>✓ {t.approve}</button></div></>:<div className={styles.blank}>{loading?'…':t.empty}</div>}</section>
  {approveOpen&&item?<div className={styles.modalBackdrop} onMouseDown={e=>{if(e.target===e.currentTarget&&!busy)setApproveOpen(false)}}><div className={`${styles.modal} ${styles.confirmModal}`} role="dialog" aria-modal="true" aria-labelledby="verification-approve-title"><div className={styles.confirmIcon}>✓</div><h3 id="verification-approve-title">{t.confirmTitle}</h3><p>{t.confirmBody}</p><div className={styles.confirmMember}><strong>{item.name}</strong><span>{item.email}</span></div><div><button onClick={()=>setApproveOpen(false)} disabled={busy}>{t.cancel}</button><button className={styles.approveSolid} onClick={()=>void resolve('approve')} disabled={busy}>{busy?'…':`✓ ${t.confirmAction}`}</button></div></div></div>:null}
  {rejectOpen&&item?<div className={styles.modalBackdrop} onMouseDown={e=>{if(e.target===e.currentTarget)setRejectOpen(false)}}><div className={styles.modal}><h3>{t.rejectTitle}</h3><p>{t.rejectHint}</p><textarea autoFocus value={reason} onChange={e=>setReason(e.target.value)} rows={5}/><div><button onClick={()=>setRejectOpen(false)}>{t.cancel}</button><button className={styles.rejectSolid} onClick={()=>void resolve('reject')} disabled={busy}>{t.sendReject}</button></div></div></div>:null}
 </div>
}
function Doc({title,url,empty}:{title:string;url?:string;empty:string}){const pdf=Boolean(url&&/\.pdf(?:\?|$)/i.test(url));return <article className={styles.docCard}><div className={styles.docTitle}>{title}</div>{url?(pdf?<iframe src={url} title={title}/>:<img src={url} alt={title}/>):<div className={styles.noFile}>{empty}</div>}</article>}
