"use client";

import { useEffect, useRef, useState } from "react";
import { useLocale } from "@/components/SiteProviders";
import { arrayOf, loadOwnProfile, profilePhotoUrl, removeProfilePhotoWeb, updateOwnProfile, uploadProfilePhotoWeb, type ProfileRow } from "@/components/profile/profileWebData";
import styles from "./PersonalProfileSettings.module.css";
import NationalityCombobox from "@/components/NationalityCombobox";

type Locale = "th"|"en"|"de";
type Form = { first_name:string; last_name:string; email:string; date_of_birth:string; height_cm:string; nationality:string; education:string; marital_status:string; gender:string };
type Lifestyle = Record<string,string[]>;
const empty:Form={first_name:"",last_name:"",email:"",date_of_birth:"",height_cm:"",nationality:"",education:"",marital_status:"",gender:""};

const COPY = {
 th:{title:"ตั้งค่าข้อมูลส่วนตัว",desc:"ข้อมูลที่ใช้แสดงบนโปรไฟล์ Melo ของคุณ",member:"หมายเลขสมาชิก",first:"ชื่อ",last:"นามสกุล",gender:"เพศ",email:"อีเมล",birthDate:"วันเดือนปีเกิด",mainPhoto:"รูปโปรไฟล์",mainPhotoDesc:"รูปโปรไฟล์หลัก (ไม่บังคับ)",height:"ส่วนสูง (ซม.)",nationality:"สัญชาติ",nationalitySearch:"พิมพ์เพื่อค้นหาสัญชาติ...",education:"การศึกษา",marital:"สถานะความสัมพันธ์",photos:"Profile Photos Gallery",photosDesc:"เพิ่มรูปภาพได้ 6 รูปนอกเหนือจากรูปโปรไฟล์หลัก",add:"เพิ่มรูป",replace:"เปลี่ยน",remove:"ลบ",save:"บันทึกข้อมูล",saving:"กำลังบันทึก...",saved:"บันทึกแล้ว",single:"โสด",married:"เคยแต่งงาน",divorced:"หย่าร้าง",widowed:"หม้าย",placeholder:"ระบุข้อมูล",looking:"กำลังมองหา",lookingGender:"เพศที่สนใจ",lookingRelationship:"ความสัมพันธ์ที่กำลังมองหา",lookingDesc:"เลือกได้มากกว่าหนึ่งคำตอบ เพื่อช่วยให้ระบบแนะนำคนที่ตรงกับคุณมากขึ้น",orientation:"รสนิยมทางเพศ",orientationDesc:"เลือกได้มากกว่าหนึ่งคำตอบ",required:"กรุณากรอกข้อมูลที่จำเป็นให้ครบ",lifestyle:"ไลฟ์สไตล์",lifestyleDesc:"ข้อมูลเหล่านี้ช่วยให้ Matching ฉลาดขึ้นและทำให้โปรไฟล์บอกความเป็นคุณได้มากขึ้น",pet:"สัตว์เลี้ยง",drink:"การดื่ม",smoke:"การสูบบุหรี่",exercise:"การออกกำลังกาย",social:"บุคลิกทางสังคม",interests:"ความสนใจ"},
 en:{title:"Personal profile",desc:"Information shown on your Melo profile",member:"Member ID",first:"First name",last:"Last name",gender:"Gender",email:"Email",birthDate:"Date of birth",mainPhoto:"Profile photo",mainPhotoDesc:"Main profile photo (optional)",height:"Height (cm)",nationality:"Nationality",nationalitySearch:"Search nationality...",education:"Education",marital:"Relationship status",photos:"Profile Photos Gallery",photosDesc:"Add up to 6 gallery photos in addition to your main profile photo",add:"Add photo",replace:"Replace",remove:"Remove",save:"Save profile",saving:"Saving...",saved:"Saved",single:"Single",married:"Previously married",divorced:"Divorced",widowed:"Widowed",placeholder:"Enter information",looking:"Looking for",lookingGender:"Interested in",lookingRelationship:"Relationship",lookingDesc:"Choose more than one option to help Melo find more relevant matches",orientation:"Sexual orientation",orientationDesc:"You can select more than one option",required:"Please complete all required information",lifestyle:"Lifestyle",lifestyleDesc:"These details help Matching understand compatibility and make profiles more expressive",pet:"Pets",drink:"Drinking",smoke:"Smoking",exercise:"Exercise",social:"Social style",interests:"Interests"},
 de:{title:"Persönliches Profil",desc:"Informationen, die in deinem Melo-Profil angezeigt werden",member:"Mitgliedsnummer",first:"Vorname",last:"Nachname",gender:"Geschlecht",email:"E-Mail",birthDate:"Geburtsdatum",mainPhoto:"Profilbild",mainPhotoDesc:"Hauptprofilbild (optional)",height:"Größe (cm)",nationality:"Nationalität",nationalitySearch:"Nationalität suchen...",education:"Ausbildung",marital:"Beziehungsstatus",photos:"Profil-Fotogalerie",photosDesc:"Füge zusätzlich zum Hauptprofilbild bis zu 6 Fotos hinzu",add:"Foto hinzufügen",replace:"Ersetzen",remove:"Entfernen",save:"Profil speichern",saving:"Speichern...",saved:"Gespeichert",single:"Single",married:"Früher verheiratet",divorced:"Geschieden",widowed:"Verwitwet",placeholder:"Information eingeben",looking:"Ich suche",lookingGender:"Interessiert an",lookingRelationship:"Beziehungsart",lookingDesc:"Mehrere Antworten sind möglich und verbessern passende Vorschläge",orientation:"Sexuelle Orientierung",orientationDesc:"Mehrere Antworten sind möglich",required:"Bitte fülle alle Pflichtfelder aus",lifestyle:"Lebensstil",lifestyleDesc:"Diese Angaben helfen beim Matching und machen dein Profil persönlicher",pet:"Haustiere",drink:"Alkohol",smoke:"Rauchen",exercise:"Sport",social:"Sozialer Typ",interests:"Interessen"}
} as const;

const OPTIONS = {
 gender:{th:["ชาย","หญิง","นอนไบนารี","อื่น ๆ","ไม่ต้องการระบุ"],en:["Man","Woman","Non-binary","Other","Prefer not to say"],de:["Mann","Frau","Nicht-binär","Andere","Keine Angabe"]},
 education:{th:["มัธยมศึกษา","ปวช. / ปวส.","ปริญญาตรี","ปริญญาโท","ปริญญาเอก","อื่น ๆ"],en:["High school","Vocational / Diploma","Bachelor's degree","Master's degree","Doctorate","Other"],de:["Schulabschluss","Berufsausbildung / Diplom","Bachelor","Master","Promotion","Andere"]},
 lookingGender:{th:["เพศชาย","เพศหญิง","LGBTQ+"],en:["Men","Women","LGBTQ+"],de:["Männer","Frauen","LGBTQ+"]},
 relationship:{th:["ความสัมพันธ์จริงจัง","คบหาดูใจ","เพื่อน","พูดคุยทำความรู้จัก","ยังไม่แน่ใจ"],en:["Long-term relationship","Dating","Friendship","Getting to know someone","Not sure yet"],de:["Feste Beziehung","Dating","Freundschaft","Kennenlernen","Noch unsicher"]},
 orientation:{th:["Straight","Gay","Lesbian","Bisexual","Pansexual","Asexual","อื่น ๆ","ไม่ต้องการระบุ"],en:["Straight","Gay","Lesbian","Bisexual","Pansexual","Asexual","Other","Prefer not to say"],de:["Heterosexuell","Schwul","Lesbisch","Bisexuell","Pansexuell","Asexuell","Andere","Keine Angabe"]},
 pet:{th:["สุนัข","แมว","นก","ปลา","สัตว์เลี้ยงอื่น ๆ","ไม่มีสัตว์เลี้ยง"],en:["Dogs","Cats","Birds","Fish","Other pets","No pets"],de:["Hunde","Katzen","Vögel","Fische","Andere Haustiere","Keine Haustiere"]},
 drink:{th:["ไม่ดื่ม","ดื่มเล็กน้อย","ดื่มตามโอกาสพิเศษ","ดื่มช่วงวันหยุด","ดื่มเป็นประจำ"],en:["Never","Rarely","Special occasions","Weekends","Regularly"],de:["Nie","Selten","Besondere Anlässe","Am Wochenende","Regelmäßig"]},
 smoke:{th:["ไม่สูบ","สูบบางครั้ง","สูบเป็นประจำ","กำลังเลิก"],en:["Never","Sometimes","Regularly","Quitting"],de:["Nie","Manchmal","Regelmäßig","Höre gerade auf"]},
 exercise:{th:["ไม่ค่อยออก","สัปดาห์ละ 1–2 ครั้ง","สัปดาห์ละ 3–4 ครั้ง","เกือบทุกวัน"],en:["Rarely","1–2 times/week","3–4 times/week","Almost daily"],de:["Selten","1–2× pro Woche","3–4× pro Woche","Fast täglich"]},
 social:{th:["Introvert","Ambivert","Extrovert"],en:["Introvert","Ambivert","Extrovert"],de:["Introvertiert","Ambivertiert","Extrovertiert"]},
 interests:{th:["Coffee","Travel","Fitness","Foodie","Music","Pets","Art","Beach"],en:["Coffee","Travel","Fitness","Foodie","Music","Pets","Art","Beach"],de:["Kaffee","Reisen","Fitness","Foodie","Musik","Haustiere","Kunst","Strand"]}
} as const;

function ChoiceGroup({title,options,value,onChange,multiple=true}:{title:string;options:readonly string[];value:string[];onChange:(v:string[])=>void;multiple?:boolean}){
 const toggle=(v:string)=>onChange(multiple?(value.includes(v)?value.filter(x=>x!==v):[...value,v]):[v]);
 return <div className={styles.choiceGroup}><strong>{title}</strong><div className={styles.chips}>{options.map(o=><button type="button" key={o} data-active={value.includes(o)} onClick={()=>toggle(o)}>{o}</button>)}</div></div>;
}

export default function PersonalProfileSettings(){
 const {locale}=useLocale(); const lang=(locale in COPY?locale:"en") as Locale; const t=COPY[lang];
 const [userId,setUserId]=useState(""); const [profile,setProfile]=useState<ProfileRow>({}); const [form,setForm]=useState<Form>(empty); const [looking,setLooking]=useState<string[]>([]); const [orientation,setOrientation]=useState<string[]>([]); const [life,setLife]=useState<Lifestyle>({}); const [busy,setBusy]=useState(false); const [msg,setMsg]=useState(""); const [uploading,setUploading]=useState<number|null>(null); const inputs=useRef<(HTMLInputElement|null)[]>([]);
 useEffect(()=>{void (async()=>{const r=await loadOwnProfile();if(!r.data)return;const p=r.data.profile||{},meta=r.data.userMetadata||{};setUserId(r.data.userId);setProfile(p);setForm({first_name:String(p.first_name||meta.first_name||""),last_name:String(p.last_name||meta.last_name||""),email:String(meta.email||""),date_of_birth:String(p.date_of_birth||""),height_cm:p.height_cm==null?"":String(p.height_cm),nationality:String(p.nationality||""),education:String(p.education||""),marital_status:String(p.marital_status||""),gender:String(p.gender||"")});setLooking(arrayOf(p.looking_for).length?arrayOf(p.looking_for):arrayOf(p.relationship_type));setOrientation(arrayOf(p.sexual_orientations).length?arrayOf(p.sexual_orientations):arrayOf(p.sexual_orientation));setLife((p.lifestyle_preferences&&typeof p.lifestyle_preferences==="object")?p.lifestyle_preferences:{});})();},[]);
 const patch=(k:keyof Form,v:string)=>{setMsg("");setForm(x=>({...x,[k]:v}));};
 const setLifeKey=(k:string,v:string[])=>{setMsg("");setLife(x=>({...x,[k]:v}));};
 async function save(){if(!userId)return;setMsg("");const relationshipOptions=new Set<string>(OPTIONS.relationship[lang]);const genderOptions=new Set<string>(OPTIONS.lookingGender[lang]);const hasLookingGender=looking.some(x=>genderOptions.has(x));const hasRelationship=looking.some(x=>relationshipOptions.has(x));const lifestyleComplete=Boolean(life.pet?.length&&life.drink?.length&&life.smoke?.length&&life.exercise?.length&&life.social?.length&&life.interests?.length);if(!form.first_name.trim()||!form.last_name.trim()||!form.gender||!form.date_of_birth||!form.height_cm||!form.nationality.trim()||!form.education||!form.marital_status||!hasLookingGender||!hasRelationship||!orientation.length||!lifestyleComplete){setMsg(t.required);return}setBusy(true);const payload={first_name:form.first_name||null,last_name:form.last_name||null,date_of_birth:form.date_of_birth||null,height_cm:form.height_cm?Number(form.height_cm):null,nationality:form.nationality||null,education:form.education||null,marital_status:form.marital_status||null,gender:form.gender||null,looking_for:looking,sexual_orientations:orientation,lifestyle_preferences:life};const r=await updateOwnProfile(userId,payload);setBusy(false);setMsg(r.error||t.saved);if(r.data)setProfile(r.data);}
 const gallery=arrayOf(profile.photo_paths).slice(1,7); const mainPhoto=profilePhotoUrl(profile,0);
 async function choose(slot:number,file?:File){if(!file)return;setUploading(slot);setMsg("");try{const r=await uploadProfilePhotoWeb({file,slotIndex:slot+1,currentPaths:arrayOf(profile.photo_paths)});setProfile(p=>({...p,photo_paths:r.paths}));}catch(e){setMsg(e instanceof Error?e.message:String(e));}finally{setUploading(null);}}
 async function remove(slot:number){setUploading(slot);try{const r=await removeProfilePhotoWeb({slotIndex:slot+1,currentPaths:arrayOf(profile.photo_paths)});setProfile(p=>({...p,photo_paths:r}));}catch(e){setMsg(e instanceof Error?e.message:String(e));}finally{setUploading(null);}}
 return <section className={styles.card}><header><span>◉</span><div><h2>{t.title}</h2><p>{t.desc}</p></div></header><div className={styles.body}>
  <div className={styles.galleryHead}><div><strong>{t.mainPhoto}</strong><small>{t.mainPhotoDesc}</small></div></div><div className={styles.gallery}><div className={styles.photo}>{mainPhoto?<img src={mainPhoto} alt=""/>:<span>＋</span>}<input ref={el=>{inputs.current[6]=el}} type="file" accept="image/*" hidden onChange={e=>{void (async()=>{const file=e.target.files?.[0];if(!file)return;setUploading(6);try{const r=await uploadProfilePhotoWeb({file,slotIndex:0,currentPaths:arrayOf(profile.photo_paths)});setProfile(p=>({...p,photo_paths:r.paths}));}catch(x){setMsg(x instanceof Error?x.message:String(x));}finally{setUploading(null)}})();e.currentTarget.value=""}}/><div className={styles.photoActions}><button disabled={uploading===6} onClick={()=>inputs.current[6]?.click()}>{mainPhoto?t.replace:t.add}</button></div></div></div>
  <div className={styles.galleryHead}><div><strong>{t.photos}</strong><small>{t.photosDesc}</small></div><b>{gallery.length}/6</b></div><div className={styles.gallery}>{Array.from({length:6}).map((_,i)=>{const url=profilePhotoUrl(profile,i+1);return <div className={styles.photo} key={i}>{url?<img src={url} alt=""/>:<span>＋</span>}<input ref={el=>{inputs.current[i]=el}} type="file" accept="image/*" hidden onChange={e=>{void choose(i,e.target.files?.[0]);e.currentTarget.value=""}}/><div className={styles.photoActions}><button disabled={uploading===i} onClick={()=>inputs.current[i]?.click()}>{url?t.replace:t.add}</button>{url?<button disabled={uploading===i} onClick={()=>void remove(i)}>{t.remove}</button>:null}</div></div>})}</div>
  <div className={styles.formGrid}><label><span>{t.member}</span><input value={userId?userId.slice(0,8).toUpperCase():"—"} disabled/></label><label><span>{t.email}</span><input value={form.email||"—"} disabled/></label><label className={styles.firstNameField}><span>{t.first} *</span><input value={form.first_name} placeholder={t.placeholder} onChange={e=>patch("first_name",e.target.value)}/></label><label><span>{t.last} *</span><input value={form.last_name} placeholder={t.placeholder} onChange={e=>patch("last_name",e.target.value)}/></label><label><span>{t.gender} *</span><select value={form.gender} onChange={e=>patch("gender",e.target.value)}><option value="">—</option>{/* MELO_GENDER_PERSISTENCE_V3 */}{form.gender&&!OPTIONS.gender[lang].includes(form.gender as never)?<option value={form.gender}>{form.gender}</option>:null}{OPTIONS.gender[lang].map(x=><option key={x} value={x}>{x}</option>)}</select></label><label><span>{t.birthDate} *</span><input type="date" value={form.date_of_birth} onChange={e=>patch("date_of_birth",e.target.value)}/></label><label><span>{t.height} *</span><input type="number" value={form.height_cm} placeholder={t.placeholder} onChange={e=>patch("height_cm",e.target.value)}/></label><label><span>{t.nationality} *</span><NationalityCombobox value={form.nationality} placeholder={t.nationalitySearch} onChange={value=>patch("nationality",value)}/></label><label><span>{t.education} *</span><select value={form.education} onChange={e=>patch("education",e.target.value)}><option value="">—</option>{form.education&&!OPTIONS.education[lang].includes(form.education as never)?<option value={form.education}>{form.education}</option>:null}{OPTIONS.education[lang].map(x=><option key={x} value={x}>{x}</option>)}</select></label><label><span>{t.marital} *</span><select value={form.marital_status} onChange={e=>patch("marital_status",e.target.value)}><option value="">—</option><option value="single">{t.single}</option><option value="previously_married">{t.married}</option><option value="divorced">{t.divorced}</option><option value="widowed">{t.widowed}</option></select></label></div>
  <div className={styles.preferenceSection}><div className={styles.sectionHead}><h3>{t.looking}</h3><p>{t.lookingDesc}</p></div><div className={styles.lookingGrid}><ChoiceGroup title={`${t.lookingGender} *`} options={OPTIONS.lookingGender[lang]} value={looking} onChange={v=>{const relationshipOptions=new Set<string>(OPTIONS.relationship[lang]);setLooking([...looking.filter(x=>relationshipOptions.has(x)),...v]);}}/><ChoiceGroup title={`${t.lookingRelationship} *`} options={OPTIONS.relationship[lang]} value={looking} onChange={v=>{const genderOptions=new Set<string>(OPTIONS.lookingGender[lang]);setLooking([...looking.filter(x=>genderOptions.has(x)),...v]);}}/></div></div>
  <div className={styles.preferenceSection}><div className={styles.sectionHead}><h3>{t.orientation}</h3><p>{t.orientationDesc}</p></div><ChoiceGroup title={`${t.orientation} *`} options={OPTIONS.orientation[lang]} value={orientation} onChange={setOrientation}/></div>
  <div className={styles.preferenceSection}><div className={styles.sectionHead}><h3>{t.lifestyle}</h3><p>{t.lifestyleDesc}</p></div><div className={styles.lifestyleGrid}><ChoiceGroup title={`${t.pet} *`} options={OPTIONS.pet[lang]} value={life.pet||[]} onChange={v=>setLifeKey("pet",v)}/><ChoiceGroup title={`${t.drink} *`} options={OPTIONS.drink[lang]} value={life.drink||[]} onChange={v=>setLifeKey("drink",v)} multiple={false}/><ChoiceGroup title={`${t.smoke} *`} options={OPTIONS.smoke[lang]} value={life.smoke||[]} onChange={v=>setLifeKey("smoke",v)} multiple={false}/><ChoiceGroup title={`${t.exercise} *`} options={OPTIONS.exercise[lang]} value={life.exercise||[]} onChange={v=>setLifeKey("exercise",v)} multiple={false}/><ChoiceGroup title={`${t.social} *`} options={OPTIONS.social[lang]} value={life.social||[]} onChange={v=>setLifeKey("social",v)} multiple={false}/><ChoiceGroup title={`${t.interests} *`} options={OPTIONS.interests[lang]} value={life.interests||[]} onChange={v=>setLifeKey("interests",v)}/></div></div>
  <div className={styles.saveBar}><span data-error={msg!==""&&msg!==t.saved}>{msg}</span><button disabled={busy} onClick={()=>void save()}>{busy?t.saving:t.save}</button></div>
 </div></section>;
}


